### ISSUE TITLE
No module named appengine.tools

### ISSUE THREAD

**Issue by 4ft35t** [phuslu/goproxy#1008]
linux 下上传报错，windows 上传正常

```python
Traceback (most recent call last):
  File "uploader.py", line 92, in <module>
    from google.appengine.tools import appengine_rpc, appcfg
ImportError: No module named appengine.tools
```

**Comment by jzp820927** [comment]
没遇到过这种错误，是什么 linux 系统？

**Comment by phuslu** [comment]
不能复现

**Comment by 4ft35t** [comment]
```bash
root@v3:/tmp# wget https://nodeload.github.com/phuslu/goproxy/legacy.zip/server.gae
--2016-08-02 22:22:09--  https://nodeload.github.com/phuslu/goproxy/legacy.zip/server.gae
正在解析主机 nodeload.github.com (nodeload.github.com)... 192.30.253.121
正在连接 nodeload.github.com (nodeload.github.com)|192.30.253.121|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 12294652 (12M) [application/zip]
正在保存至: “server.gae”

100%[=============================================================================================>] 12,294,652  5.81MB/s   用时 2.0s

2016-08-02 22:22:12 (5.81 MB/s) - 已保存 “server.gae” [12294652/12294652])

root@v3:/tmp# unzip -q server.gae
root@v3:/tmp# cd phuslu-goproxy-8014116/
root@v3:/tmp/phuslu-goproxy-8014116# ls
gae  google_appengine  python27.dll  python27.exe  python27.zip  uploader.bat  uploader.py
root@v3:/tmp/phuslu-goproxy-8014116# python uploader.py
Loading Google Appengine SDK...
警告：建议先启动 GoProxy 客户端或者 VPN 然后再上传，如果您的 VPN 已经打开的话，请按回车键继续。

Traceback (most recent call last):
  File "uploader.py", line 92, in <module>
    from google.appengine.tools import appengine_rpc, appcfg
ImportError: No module named appengine.tools
```
环境设置
```bash
root@v3:/tmp/phuslu-goproxy-8014116# echo $PATH
/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin:/opt/node/bin:/usr/local/go/bin
root@v3:/tmp/phuslu-goproxy-8014116# echo $PYTHONPATH

root@v3:/tmp/phuslu-goproxy-8014116# uname -a
Linux v3 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 i686 i686 i686 GNU/Linux
root@v3:/tmp/phuslu-goproxy-8014116# cat /etc/issue
Ubuntu 14.04.4 LTS \n \l
```

**Comment by 4ft35t** [comment]
另外一台 vps 上是正常的
```bash
root@default:/tmp# unzip -q server.gae
root@default:/tmp# cd phuslu-goproxy-8014116/
root@default:/tmp/phuslu-goproxy-8014116# python uploader.py
Loading Google Appengine SDK...
警告：建议先启动 GoProxy 客户端或者 VPN 然后再上传，如果您的 VPN 已经打开的话，请按回车键继续。
===============================================================
 GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备。
APPID:test
10:28 PM Application: test
10:28 PM Host: appengine.google.com
10:28 PM Rolling back the update.
Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=550516889912.apps.googleusercontent.com&access_type=offline

Enter verification code:
Authentication has failed: invalid_requestMissing required parameter: code
```

环境设置
```
root@default:/tmp/phuslu-goproxy-8014116# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
root@default:/tmp/phuslu-goproxy-8014116# echo $PYTHONPATH


root@default:/tmp/phuslu-goproxy-8014116# uname -a
Linux default 2.6.32-042stab116.1 #1 SMP Wed May 4 16:21:02 MSK 2016 i686 i686 i686 GNU/Linux
root@default:/tmp/phuslu-goproxy-8014116# cat /etc/issue
Ubuntu 14.04.4 LTS \n \l
```

**Comment by jzp820927** [comment]
ununtu 我部署过很多次，都没遇到过类似问题。是不是文件下载不完整？

**Comment by 4ft35t** [comment]
两台 vps 上下载的文件 md5 都是 00dc05e745a3cb859252f8ab555f838f
本地 Mac 上也是同样地错误

**Comment by jzp820927** [comment]
太不科学啊，应该是个例吧，会不会是系统问题，或者 python 问题

**Comment by 4ft35t** [comment]
找到原因了，很早以前装了老版本的 appengine， 然后 google 变成了 built-in
```python
In [1]: import google

In [2]: google
Out[2]: <module 'google' (built-in)>
```
老版本的 appengine 没这些方法，导致报错。
appengine 改写了 built-in，在 virtualenv 里也有 google 模块。
我试试不升级 appengine 如何修改。

**Comment by phuslu** [comment]
谢谢提供线索，已修复 https://github.com/phuslu/goproxy/commit/0c65a22aca6c7c2659cc5f2a3131d09cd3bec30a

**Comment by 4ft35t** [comment]
补丁无效，built-in 的优先级高于 path, 已经在 built-in 找到了，不再查找 path。
我在导入前把 google module 删除可以工作
```py
del sys.modules['google']
```

**Comment by phuslu** [comment]
谢谢，能否提个 pull request？
