### ISSUE TITLE
如何全部强制GAE

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1026]
gfwlist.txt这个列表已经过时, 很多国外网站直接不通, 或者很不稳定.
智能切换其实很愚昧.

是否httpproxy.json里面
            // "autoproxy",
就可以全部走GAE?

**Comment by Kisesy** [comment]
gfwlist.txt 只有用pac才会用到，直接用8087是跟这个没关系的

**Comment by jzp820927** [comment]
httpproxy.json里面
gae 放在第一位应该就可以了吧。

**Comment by distance00** [comment]
从来不用autoproxy，我把"RequestFilters"和"RoundTripFilters"中的autoproxy都删了。autoproxy.json中全部"Enabled": false

**Comment by jasonliul** [comment]
@jzp820927 
			// "direct",
把直连禁用才行, 切换来去, 速度很不稳定.
近几天的问题....

**Comment by Kisesy** [comment]
你这看来是谷歌中国有问题了
应该把gae.json下的 SiteToAlias 里的网址，除了 ` "*.appspot.com": "google_hk",` 之外的全部注释掉
这样全部网址都走GAE

**Comment by jzp820927** [comment]
我这边 google 中国正常

**Comment by phuslu** [comment]
奇怪，一直未见。

建议把所有的 google_cn 改成 google_hk 试试

**Comment by jasonliul** [comment]
@Kisesy @phuslu 
今天已经恢复中国谷歌, 很奇怪的, 我用路由器ping通, 然后本机才恢复ping通状态.
只是如果有一些直连的话, 速度起伏很大.

google_cn 段全部填写国外ip, 也是一样.

这个问题就是近几天的事情, 而且并不像破墙作怪, 所以搞不懂.

**Comment by jasonliul** [comment]
上次升级了06.22服务端, 近期谷歌好像有些调整, 会不会是这个问题?

**Comment by MeABc** [comment]
借地方提问，不想新开一个：）

@phuslu 

两个问题：

a.  https://www.ssllabs.com 在这测试 Google 服务器时，发现其服务器现在好像都没有支持压缩   
 `SSL/TLS compression    No`

那么这个 `"DisableCompression": false,` 是不是默认改成 true ？

b.  关于 `http2.StreamError` 这个的，我 Google 一下，找到 https://github.com/golang/go/issues/15425 这里。   

呃，我想说的是，是不是 golang 的问题。你看下。

**Comment by MeABc** [comment]
关于问题二补充，我是这样想的，在 ForceHTTP2 时，只有几个 Google 域名访问才会出现这种 `http2.StreamError`  。如 groups.google.com 。

我在这里 https://tools.keycdn.com/http2-test 测试，我找到的 IP 和 groups.google.com ，或者是本地 
nslookup groups.google.com 得到的 IP 放在 https://tools.keycdn.com/http2-test 里测试，结果都是 h2 服务器，所以猜想是不是 golang 的问题。

**Comment by Kisesy** [comment]
@phuslu 
看到 @MeABc 说到 compression
我发现GAE端对deflate支持还是有问题，打开 http://httpbin.org/deflate，PHP端打开正常，但GAE完蛋

**Comment by phuslu** [comment]
@MeABc 
1. `"DisableCompression": false` 是指 Accept: Gzip ， 和 ssl compression 无关。如 @Kisesy 所说
2. 有这个可能，我接下来跟踪一下。

@Kisesy 
这个是 GAE 的 urlfetch 的问题，虽说在 goproxy 客户端也能修复，但是会伤害效率，所以一直忧郁。
目前的过度方案是 ForceDeflate -- 遇到这种网站，需要自己把域名加到这个选项即可。
逻辑在 https://github.com/phuslu/goproxy/blob/master/httpproxy/filters/gae/gae.go#L480

**Comment by phuslu** [comment]
不过你这倒提示了我，可以在 goproxy 服务段用反射的方法检测到，这样就不会影响效率了。

谢谢反馈。

**Comment by MeABc** [comment]
"DisableCompression": false 

这个我一直理解还以为是 SSL/TLS 里的 Compression 。囧

**Comment by phuslu** [comment]
@Kisesy 

最新版的 go 版服务端和 r889 已经彻底修复乱码问题，请帮忙验证。

再次感谢反馈。

**Comment by MeABc** [comment]
再补充一下问题二 。。。。

ForceHTTP2 时，直连 www.youtube.com 会提示 http2.StreamError ，但页面正常。奇怪。

希望这个有帮到社长。

**Comment by Kisesy** [comment]
@phuslu 试了下，确实没问题...

**Comment by phuslu** [comment]
呵呵，这个修复有点灵机一动的感觉。

**Comment by Kisesy** [comment]
```
GoProxy Version    : r890 (go/6780ee3 http2/f6f1b74 windows/386)
GoProxy Profile    : Default
Listen Address     : 127.0.0.1:8087
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://127.0.0.1:8087/proxy.pac
GoProxy Profile    : PHP
Listen Address     : 127.0.0.1:8088
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,php|autorange
Pac Server         : http://127.0.0.1:8088/proxy.pac
------------------------------------------------------
fatal error: concurrent map read and map write

goroutine 20 [running]:
runtime.throw(0x867fc6, 0x21)
	/tmp/goproxy.20160808.27935/go/src/runtime/panic.go:566 +0x7f fp=0x20281b28 sp=0x20281b1c
runtime.mapaccess2_faststr(0x7fa220, 0x202fe3c0, 0x20542320, 0x8, 0x1, 0x0)
	/tmp/goproxy.20160808.27935/go/src/runtime/hashmap_fast.go:306 +0x5d fp=0x20281b6c sp=0x20281b28
_/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters.GetFilter(0x20542320, 0x8, 0x0, 0x0, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/filters.go:54 +0x5b fp=0x20281bd4 sp=0x20281b6c
_/tmp/goproxy.20160808.27935/goproxy/httpproxy.getFilters(0x20542390, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/httpproxy.go:98 +0x3ed fp=0x20281e38 sp=0x20281bd4
_/tmp/goproxy.20160808.27935/goproxy/httpproxy.ServeProfile(0x20542390, 0x3, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/httpproxy.go:66 +0x2e1 fp=0x20281fc0 sp=0x20281e38
runtime.goexit()
	/tmp/goproxy.20160808.27935/go/src/runtime/asm_386.s:1612 +0x1 fp=0x20281fc4 sp=0x20281fc0
created by main.main
	/tmp/goproxy.20160808.27935/goproxy/main.go:71 +0xd69

goroutine 1 [select (no cases)]:
main.main()
	/tmp/goproxy.20160808.27935/goproxy/main.go:75 +0x6bc

goroutine 18 [chan receive]:
github.com/phuslu/glog.(*loggingT).flushDaemon(0xa1a5a0)
	/tmp/goproxy.20160808.27935/gopath/src/github.com/phuslu/glog/glog.go:897 +0x65
created by github.com/phuslu/glog.init.1
	/tmp/goproxy.20160808.27935/gopath/src/github.com/phuslu/glog/glog.go:410 +0x1e1

goroutine 19 [runnable, locked to thread]:
syscall.Syscall9(0x75526ccf, 0x8, 0x0, 0x16d1c0, 0x0, 0x1720f8, 0x207953d8, 0x0, 0x0, 0x20795370, ...)
	/tmp/goproxy.20160808.27935/go/src/runtime/syscall_windows.go:185 +0x4a
syscall.CertGetCertificateChain(0x0, 0x16d1c0, 0x0, 0x1720f8, 0x207953d8, 0x0, 0x0, 0x20795370, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/go/src/syscall/zsyscall_windows.go:1141 +0xaf
crypto/x509.(*Certificate).systemVerify(0x2077c240, 0x20795544, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/go/src/crypto/x509/root_windows.go:200 +0x390
crypto/x509.(*Certificate).Verify(0x2077c240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/goproxy.20160808.27935/go/src/crypto/x509/verify.go:239 +0x12b
_/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl.NewRootCA(0x20525848, 0x7, 0x2da30000, 0x7009d3, 0x800, 0x20525818, 0x5, 0x1, 0xe, 0x0, ...)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl/rootca.go:160 +0x1158
_/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl.NewFilter.func1()
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl/stripssl.go:80 +0xa4
sync.(*Once).Do(0xa2bca8, 0x20795b3c)
	/tmp/goproxy.20160808.27935/go/src/sync/once.go:44 +0xcf
_/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl.NewFilter(0x205342d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl/stripssl.go:84 +0x82
_/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl.init.1.func1(0x0, 0x0, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/stripssl/stripssl.go:60 +0x34
_/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters.GetFilter(0x20542260, 0x8, 0x0, 0x0, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/filters.go:63 +0x17b
_/tmp/goproxy.20160808.27935/goproxy/httpproxy.getFilters(0x205422e0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/httpproxy.go:98 +0x3ed
_/tmp/goproxy.20160808.27935/goproxy/httpproxy.ServeProfile(0x205422e0, 0x7, 0x0, 0x0)
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/httpproxy.go:66 +0x2e1
created by main.main
	/tmp/goproxy.20160808.27935/goproxy/main.go:71 +0xd69

goroutine 23 [runnable]:
sync.(*Once).Do(0xa2bc98, 0x2053c570)
	/tmp/goproxy.20160808.27935/go/src/sync/once.go:35
created by _/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/autoproxy.NewFilter
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/autoproxy/autoproxy.go:198 +0xf06

goroutine 5 [runnable]:
sync.(*Once).Do(0xa2bc98, 0x2027c0b0)
	/tmp/goproxy.20160808.27935/go/src/sync/once.go:35
created by _/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/autoproxy.NewFilter
	/tmp/goproxy.20160808.27935/goproxy/httpproxy/filters/autoproxy/autoproxy.go:198 +0xf06
```

@phuslu 最近打开，偶尔会出错误，重载之后会正常

**Comment by phuslu** [comment]
啊，谢谢反馈，此处有 bug，是修复内存占用较高的那个 commit 引入的。

我看下。

**Comment by phuslu** [comment]
@Kisesy 貌似这个问题在 64 位平台不能复现，我在 r891 尝试修复，请验证一下。

**Comment by Kisesy** [comment]
@phuslu 其实是我把 "autoproxy" 加到 php 的 "RequestFilters" 里的缘故……

**Comment by Kisesy** [comment]
@phuslu 还是回退代码吧，新版直接启动卡住不动了

**Comment by phuslu** [comment]
@Kisesy 惭愧，回退了 :trollface:

**Comment by distance00** [comment]
@Kisesy php也支持autorange吗？默认怎么没有加上，实现起来应该和age不一样吧？

**Comment by Kisesy** [comment]
@distance00 额，我说的是 autoproxy

**Comment by MeABc** [comment]
@phuslu 

把 "httpbin.org": "php",   加到 autoproxy.json 的 SiteFilters 里，它不走 “php”，只走 “gae”？ 但，走 8088 的话就正常。

@Kisesy 

![ddfd](https://cloud.githubusercontent.com/assets/18194126/17506656/4763360a-5e3d-11e6-9b50-5e18ede8cbfc.png)

这网站还检测浏览器？

**Comment by Kisesy** [comment]
@MeABc 不检测浏览器，它只会返回 json，浏览器有各自的显示方式，例如IE就直接下载json文件 (笑

**Comment by MeABc** [comment]
社长， golang 的 issues 中 （问题二），我看到他们的测试服务器是 h2 ，那 GoProxy 的 go.server 是不是也可以（写成）支持 H2 ？ 这会有性能提升不？

**Comment by phuslu** [comment]
@Kisesy 请看下 https://github.com/phuslu/goproxy/issues/1033 又一次修复了 :trollface:

**Comment by phuslu** [comment]
@MeABc 和 go server 无关，是 GFE 的功能。

**Comment by MeABc** [comment]
> 那 GoProxy 的 go.server 是不是也可以（写成）支持 H2

我这里的 go.server 是指本地监听服务器
