### ISSUE TITLE
上传服务端报错是什么情况...之前一直用的goa的服务端，想更新到gop的，结果报错。

### ISSUE THREAD

**Issue by xc1988** [phuslu/goproxy#1042]
APPID:******
04:06 PM Application: ********
04:06 PM Host: appengine.google.com
04:06 PM Rolling back the update.
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\uploader.py", line 131,
in <module>
    main()
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\uploader.py", line 117,
in main
    upload('gae', appid)
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\uploader.py", line 100,
in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 2951, in Run
    self.action(self)
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 5044, in __call__
    return method()
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 4397, in Rollback
    self._Rollback()
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 4442, in _Rollback
    appversion.Rollback(force_rollback)
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 2362, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "D:\Program Files\goproxy\phuslu-goproxy-42a4766\google_appengine\google\
appengine\tools\appcfg.py", line 1696, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line
 247, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "google_appengine\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060]
请按任意键继续. . .

**Comment by jzp820927** [comment]
不明觉厉，是严格验证 wiki 教程操作的吗？

**Comment by xc1988** [comment]
@jzp820927 wiki就那两个步骤，不可能搞错

**Comment by jzp820927** [comment]
一直都要开代理的，不开代理，你能连上 google？
