### ISSUE TITLE
autoproxy.json中"RegionFilters"不能true

### ISSUE THREAD

**Issue by yhyhnk** [phuslu/goproxy#1045]
win7 64位 r906
设为true,其它项未改, 启动gop闪退,是什么原因? 即使重新修改回来(false)依然 闪退.

**Comment by phuslu** [comment]
不能复现，推测你的配置不正确。

**Comment by yhyhnk** [comment]
ERROR: logging before flag.Parse: F0812 12:20:50.047491    5380 autoproxy.go:90]
 storage.ReadJsonConfig("autoproxy.json") failed: invalid character 'ï' looking
for beginning of value
goroutine 1 [running, locked to thread]:
github.com/phuslu/glog.stacks(0xb08700, 0xc000000000, 0x96, 0xe6)
        /tmp/goproxy.20160811.9905/gopath/src/github.com/phuslu/glog/glog.go:784
 +0xac
github.com/phuslu/glog.(*loggingT).output(0xaeba60, 0xc000000003, 0xc0421aac00,
0xabc9ea, 0xc, 0x5a, 0x0)
        /tmp/goproxy.20160811.9905/gopath/src/github.com/phuslu/glog/glog.go:735
 +0x307
github.com/phuslu/glog.(*loggingT).printf(0xaeba60, 0xc000000003, 0x8dd78e, 0x26
, 0xc042077ec0, 0x2, 0x2)
        /tmp/goproxy.20160811.9905/gopath/src/github.com/phuslu/glog/glog.go:655
 +0x153
github.com/phuslu/glog.Fatalf(0x8dd78e, 0x26, 0xc042077ec0, 0x2, 0x2)
        /tmp/goproxy.20160811.9905/gopath/src/github.com/phuslu/glog/glog.go:116
3 +0x6e
_/tmp/goproxy.20160811.9905/goproxy/httpproxy/filters/autoproxy.init.1()
        /tmp/goproxy.20160811.9905/goproxy/httpproxy/filters/autoproxy/autoproxy
.go:90 +0x40e
_/tmp/goproxy.20160811.9905/goproxy/httpproxy/filters/autoproxy.init()
        /tmp/goproxy.20160811.9905/goproxy/httpproxy/filters/autoproxy/autoproxy
_pac.go:310 +0xb1
_/tmp/goproxy.20160811.9905/goproxy/httpproxy.init()
        /tmp/goproxy.20160811.9905/goproxy/httpproxy/httpproxy.go:139 +0x89
main.init()
        /tmp/goproxy.20160811.9905/goproxy/main.go:78 +0x53

**Comment by yhyhnk** [comment]
请P大帮看一下,是哪里的毛病?

**Comment by phuslu** [comment]
`storage.ReadJsonConfig("autoproxy.json") failed: invalid character 'ï' looking
for beginning of value`

报错是说 autoproxy.json 不合法，但是不能推出你到底是什么地方出错了。

**Comment by jzp820927** [comment]
是不是用记事本改了配置文件，导致格式问题

**Comment by yhyhnk** [comment]
@phuslu @jzp820927  我的天,多么痛的领悟, 打开记事本用ANSI编码保存就OK了. 谢谢!

**Comment by phuslu** [comment]
恐怕不行，这个得保存为 utf8 without bom 类型。

**Comment by jzp820927** [comment]
记事本默认就是报错为 ansi 编码，除非你手动改动编码。

**Comment by wenliyang** [comment]
推荐使用 Notepad2 或 Notepad++，不要用记事本来修改

**Comment by yhyhnk** [comment]
记事本打开用ansi编码保存和notepad++打开用ansi、utf-8 without bom编码保存,都不会出现闪退, 不过以后一定用utf-8 without bom, 省心.

**Comment by blob2015** [comment]
不用记事本最省心……
