### ISSUE TITLE
大神们，请问如下错误怎么解决呢，谢谢啦

### ISSUE THREAD

**Issue by MEOWMEOWMOMODA** [phuslu/goproxy#1051]
ERROR: logging before flag.Parse: F0814 21:35:45.932141    4504 gae.go:98] storage.ReadJsonConfig("gae.json") failed: invalid character '"' after array element
goroutine 1 [running, locked to thread]:
github.com/phuslu/glog.stacks(0xa2dc00, 0x0, 0x0, 0x0)
        /tmp/goproxy.20160814.26327/gopath/src/github.com/phuslu/glog/glog.go:784 +0xac
github.com/phuslu/glog.(*loggingT).output(0xa1c640, 0x3, 0x11069b80, 0x9f7357, 0x6, 0x62, 0x0)
        /tmp/goproxy.20160814.26327/gopath/src/github.com/phuslu/glog/glog.go:735 +0x26d
github.com/phuslu/glog.(*loggingT).printf(0xa1c640, 0x3, 0x86b870, 0x26, 0x10f77f68, 0x2, 0x2)
        /tmp/goproxy.20160814.26327/gopath/src/github.com/phuslu/glog/glog.go:655 +0x14e
github.com/phuslu/glog.Fatalf(0x86b870, 0x26, 0x10f77f68, 0x2, 0x2)
        /tmp/goproxy.20160814.26327/gopath/src/github.com/phuslu/glog/glog.go:1163 +0x52
_/tmp/goproxy.20160814.26327/goproxy/httpproxy/filters/gae.init.1()
        /tmp/goproxy.20160814.26327/goproxy/httpproxy/filters/gae/gae.go:98 +0x178
_/tmp/goproxy.20160814.26327/goproxy/httpproxy/filters/gae.init()
        /tmp/goproxy.20160814.26327/goproxy/httpproxy/filters/gae/gaetransport.go:135 +0xc9
_/tmp/goproxy.20160814.26327/goproxy/httpproxy.init()
        /tmp/goproxy.20160814.26327/goproxy/httpproxy/httpproxy.go:139 +0xa1
main.init()
        /tmp/goproxy.20160814.26327/goproxy/main.go:78 +0x5c

**Comment by wenliyang** [comment]
编辑设置文件请用 Notepad2 或 Notepad++，不要用记事本

**Comment by jzp820927** [comment]
ERROR: logging before flag.Parse: F0814 21:35:45.932141 4504 gae.go:98] storage.ReadJsonConfig("gae.json") failed: invalid character '"' after array element

这不是很明显的告诉你了，gae.json 文件格式错误，检查修改下就行了。

**Comment by MEOWMEOWMOMODA** [comment]
原来是多个APPID后面要有个“逗号”隔开，看教程不仔细啊╮(￣▽￣)╭
