### ISSUE TITLE
当iphone共享pac时，出现下列错误，疯狂刷屏，瞬间占满cpu

### ISSUE THREAD

**Issue by inkdie** [phuslu/goproxy#1312]
W1122 01:50:29.864446    9764 gaetransport.go:116] GAE: 个人ID-9.appspot.com
urlfetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get
 DEADLINE_EXCEEDED, retry with deadline=14s...
W1122 01:50:29.864946    9764 gaetransport.go:116] GAE: 个人ID-9.appspot.com
urlfetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get
 DEADLINE_EXCEEDED, retry with deadline=14s...
W1122 01:50:29.878458    9764 gaetransport.go:116] GAE: 个人ID-9.appspot.com
urlfetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get
 DEADLINE_EXCEEDED, retry with deadline=14s...
W1122 01:50:02.400630    9764 gaetransport.go:116] GAE: 个人ID-10.appspot.com
 urlfetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" ge
t DEADLINE_EXCEEDED, retry with deadline=14s...
I1122 01:49:48.936273    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=300, bad_addrs=564
I1122 01:50:29.909293    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=338, bad_addrs=567
W1122 01:50:29.980862    9764 gaetransport.go:49] GAE: "GET http://个人IP:
8087/apple-touch-icon-120x120-precomposed.png" timeout: net/http: timeout awaiti
ng response headers, helpers.CloseConnections(*http.Transport)
W1122 01:51:32.843052    9764 gaetransport.go:56] GAE: request "http://个人IP73
.62:8087/apple-touch-icon-120x120-precomposed.png" error: *http.httpError(net/ht
tp: timeout awaiting response headers), retry...
W1122 01:50:30.001585    9764 gaetransport.go:116] GAE: 个人ID-3.appspot.com url
fetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get DE
ADLINE_EXCEEDED, retry with deadline=14s...
W1122 01:50:30.002086    9764 gaetransport.go:49] GAE: "GET http://个人IP:
8087/apple-touch-icon-120x120-precomposed.png" timeout: net/http: timeout awaiti
ng response headers, helpers.CloseConnections(*http.Transport)
W1122 01:51:32.895257    9764 gaetransport.go:56] GAE: request "http://个人IP73
.62:8087/apple-touch-icon-120x120-precomposed.png" error: *http.httpError(net/ht
tp: timeout awaiting response headers), retry...
W1122 01:50:30.007591    9764 gaetransport.go:49] GAE: "GET http://个人IP:
8087/apple-touch-icon-120x120-precomposed.png" timeout: net/http: timeout awaiti
ng response headers, helpers.CloseConnections(*http.Transport)
I1122 01:50:30.049406    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=338, bad_addrs=567
I1122 01:50:30.066924    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=338, bad_addrs=567
W1122 01:50:30.072430    9764 gaetransport.go:116] GAE: 个人ID-3.appspot.com url
fetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get DE
ADLINE_EXCEEDED, retry with deadline=14s...
I1122 01:50:02.529736    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=320, bad_addrs=564
W1122 01:50:30.085942    9764 gaetransport.go:49] GAE: "GET http://个人IP:
8087/apple-touch-icon-120x120-precomposed.png" timeout: net/http: timeout awaiti
ng response headers, helpers.CloseConnections(*http.Transport)
W1122 01:51:33.005603    9764 gaetransport.go:56] GAE: request "http://个人IP73
.62:8087/apple-touch-icon-120x120-precomposed.png" error: *http.httpError(net/ht
tp: timeout awaiting response headers), retry...
I1122 01:50:30.140621    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-2.appspot.com:443") with good_addrs=338, bad_addrs=567
W1122 01:50:02.580099    9764 gaetransport.go:116] GAE: 个人ID-6.appspot.com
urlfetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get
 DEADLINE_EXCEEDED, retry with deadline=14s...
I1122 01:51:33.056167    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-5.appspot.com:443") with good_addrs=387, bad_addrs=570
I1122 01:51:33.067657    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=387, bad_addrs=570
I1122 01:51:33.088092    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=387, bad_addrs=570
I1122 01:50:30.229955    9764 gae.go:571] 107.178.195.130:47690 "GAE FETCH GET h
ttp://个人IP:8087/apple-touch-icon-120x120-precomposed.png HTTP/1.1" 200 2
04
W1122 01:51:33.102293    9764 gaetransport.go:116] GAE: 个人ID-2.appspot.com url
fetch "http://个人IP:8087/apple-touch-icon-120x120-precomposed.png" get DE
ADLINE_EXCEEDED, retry with deadline=14s...
I1122 01:49:48.943780    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "个人ID
-3.appspot.com:443") with good_addrs=300, bad_addrs=564
I1122 01:50:30.281004    9764 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "bjliu2
008.appspot.com:443") with good_addrs=337, bad_addrs=567

**Comment by inkdie** [comment]
重启程序，继续黄字刷屏
goroutine 210957 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x0, 0x28b7d7c0, 0xa25152, 0
xa, 0x62, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x0, 0x867785, 0x3f, 0x2df8b
bf8, 0x4, 0x4)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Verbose.Infof(0x7df301, 0x867785, 0x3f, 0x2df8bbf8, 0x4,
0x4)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1063
 +0x60
_/tmp/goproxy.161120.22142/goproxy/httpproxy/helpers.(*MultiDialer).DialTLS2(0x1
10b8000, 0x84b6db, 0x3, 0x1ebd7080, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/helpers/dialer2.go:98 +0x1f3
_/tmp/goproxy.161120.22142/goproxy/httpproxy/helpers.(*MultiDialer).DialTLS(0x11
0b8000, 0x84b6db, 0x3, 0x1ebd7080, 0x1c, 0xa70e20, 0x0, 0x0, 0x4ba160)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/helpers/dialer2.go:91 +0x49
_/tmp/goproxy.161120.22142/goproxy/httpproxy/helpers.(*MultiDialer).DialTLS-fm(0
x84b6db, 0x3, 0x1ebd7080, 0x1c, 0x5, 0x1a5b4660, 0xd, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:260 +0x40
net/http.(*Transport).dialConn(0x110ce0a0, 0xa31b60, 0x1108214c, 0x0, 0x84c6db,
0x5, 0x1ebd7080, 0x1c, 0x11120020, 0x0, ...)
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:1027 +0x307
net/http.(*Transport).getConn.func4(0x110ce0a0, 0xa31b60, 0x1108214c, 0x1ebd70a0
, 0x23ea9100)
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:954 +0x3e
created by net/http.(*Transport).getConn
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:956 +0x2b0

goroutine 43790 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x0, 0x2b7c2b40, 0xa2383a, 0
x6, 0x23b, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x0, 0x85a892, 0x1a, 0x170b3
b1c, 0x7, 0x7)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Verbose.Infof(0x7dfa01, 0x85a892, 0x1a, 0x170b3b1c, 0x7,
0x7)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1063
 +0x60
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Filter).RoundTrip(0x1
12ea500, 0xa31be0, 0x17a1d360, 0x13064080, 0xa31be0, 0x17a1d360, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:571 +0xa2
8
_/tmp/goproxy.161120.22142/goproxy/httpproxy.Handler.ServeHTTP(0xa31ae0, 0x1111a
100, 0x112fa7e0, 0x3, 0x4, 0x112fa800, 0x3, 0x4, 0x11120070, 0x1, ...)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/handler.go:89 +0x41c
_/tmp/goproxy.161120.22142/goproxy/httpproxy.(*Handler).ServeHTTP(0x1111a440, 0x
a313a0, 0x1bb70990, 0x14f74a00)
        <autogenerated>:1 +0x56
net/http.serverHandler.ServeHTTP(0x114aa100, 0xa313a0, 0x1bb70990, 0x14f74a00)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2558 +0x70
net/http.(*conn).serve(0x140d4c60, 0xa31b20, 0x167e76c0)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:1815 +0x578
created by net/http.(*Server).Serve
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2658 +0x225

goroutine 152132 [chan receive, 6 minutes]:
net/http.(*Transport).getConn.func2.1(0x2cd5a1c0, 0x110ce0a0, 0x86b044)
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:943 +0x4b
created by net/http.(*Transport).getConn.func2
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:947 +0x61

goroutine 119340 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x0, 0x18651a40, 0xa25152, 0
xa, 0x62, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x0, 0x867785, 0x3f, 0x173f1
bf8, 0x4, 0x4)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Verbose.Infof(0x7df301, 0x867785, 0x3f, 0x173f1bf8, 0x4,
0x4)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1063
 +0x60
_/tmp/goproxy.161120.22142/goproxy/httpproxy/helpers.(*MultiDialer).DialTLS2(0x1
10b8000, 0x84b6db, 0x3, 0x137fdf60, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/helpers/dialer2.go:98 +0x1f3
_/tmp/goproxy.161120.22142/goproxy/httpproxy/helpers.(*MultiDialer).DialTLS(0x11
0b8000, 0x84b6db, 0x3, 0x137fdf60, 0x1c, 0xa70e20, 0x0, 0x0, 0x4ba160)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/helpers/dialer2.go:91 +0x49
_/tmp/goproxy.161120.22142/goproxy/httpproxy/helpers.(*MultiDialer).DialTLS-fm(0
x84b6db, 0x3, 0x137fdf60, 0x1c, 0x5, 0x1924a6a0, 0xd, 0x1b28fc50)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:260 +0x40
net/http.(*Transport).dialConn(0x110ce0a0, 0xa31b60, 0x1108214c, 0x0, 0x84c6db,
0x5, 0x137fdf60, 0x1c, 0x11120020, 0x0, ...)
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:1027 +0x307
net/http.(*Transport).getConn.func4(0x110ce0a0, 0xa31b60, 0x1108214c, 0x137fdf80
, 0x18758080)
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:954 +0x3e
created by net/http.(*Transport).getConn
        /tmp/goproxy.161120.22142/go/src/net/http/transport.go:956 +0x2b0

goroutine 148247 [semacquire, 4 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x1, 0x3b6b6aa0, 0xa237f1, 0
xf, 0x74, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x1, 0x868181, 0x45, 0x28acf
79c, 0x3, 0x3)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Warningf(0x868181, 0x45, 0x28acf79c, 0x3, 0x3)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1112
 +0x53
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Transport).RoundTrip(
0x110883f0, 0x2327cc00, 0x1a4d3df0, 0xa, 0xa)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gaetransport.go:
116 +0x94f
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Filter).RoundTrip(0x1
12ea500, 0xa31be0, 0x15109360, 0x2327cc00, 0xa31be0, 0x15109360, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:514 +0x7a
4
_/tmp/goproxy.161120.22142/goproxy/httpproxy.Handler.ServeHTTP(0xa31ae0, 0x1111a
100, 0x112fa7e0, 0x3, 0x4, 0x112fa800, 0x3, 0x4, 0x11120070, 0x1, ...)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/handler.go:89 +0x41c
_/tmp/goproxy.161120.22142/goproxy/httpproxy.(*Handler).ServeHTTP(0x1111a440, 0x
a313a0, 0x2606fef0, 0x171fd580)
        <autogenerated>:1 +0x56
net/http.serverHandler.ServeHTTP(0x114aa100, 0xa313a0, 0x2606fef0, 0x171fd580)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2558 +0x70
net/http.(*conn).serve(0x24e318c0, 0xa31b20, 0x16a28a60)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:1815 +0x578
created by net/http.(*Server).Serve
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2658 +0x225

goroutine 145623 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x1, 0x363ce780, 0xa237f1, 0
xf, 0x74, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x1, 0x868181, 0x45, 0x1efd3
79c, 0x3, 0x3)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Warningf(0x868181, 0x45, 0x1efd379c, 0x3, 0x3)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1112
 +0x53
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Transport).RoundTrip(
0x110883f0, 0x1e008100, 0x1b73fb50, 0xa, 0xa)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gaetransport.go:
116 +0x94f
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Filter).RoundTrip(0x1
12ea500, 0xa31be0, 0x15793800, 0x1e008100, 0xa31be0, 0x15793800, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:514 +0x7a
4
_/tmp/goproxy.161120.22142/goproxy/httpproxy.Handler.ServeHTTP(0xa31ae0, 0x1111a
100, 0x112fa7e0, 0x3, 0x4, 0x112fa800, 0x3, 0x4, 0x11120070, 0x1, ...)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/handler.go:89 +0x41c
_/tmp/goproxy.161120.22142/goproxy/httpproxy.(*Handler).ServeHTTP(0x1111a440, 0x
a313a0, 0x1f01b710, 0x1e63da80)
        <autogenerated>:1 +0x56
net/http.serverHandler.ServeHTTP(0x114aa100, 0xa313a0, 0x1f01b710, 0x1e63da80)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2558 +0x70
net/http.(*conn).serve(0x1ce2b980, 0xa31b20, 0x15793240)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:1815 +0x578
created by net/http.(*Server).Serve
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2658 +0x225

goroutine 90474 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x1, 0x340c6640, 0xa237f1, 0
xf, 0x74, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x1, 0x868181, 0x45, 0x30e41
79c, 0x3, 0x3)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Warningf(0x868181, 0x45, 0x30e4179c, 0x3, 0x3)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1112
 +0x53
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Transport).RoundTrip(
0x110883f0, 0x1bed1300, 0x111dcac0, 0xa, 0xa)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gaetransport.go:
116 +0x94f
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Filter).RoundTrip(0x1
12ea500, 0xa31be0, 0x1282ca00, 0x1bed1300, 0xa31be0, 0x1282ca00, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:514 +0x7a
4
_/tmp/goproxy.161120.22142/goproxy/httpproxy.Handler.ServeHTTP(0xa31ae0, 0x1111a
100, 0x112fa7e0, 0x3, 0x4, 0x112fa800, 0x3, 0x4, 0x11120070, 0x1, ...)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/handler.go:89 +0x41c
_/tmp/goproxy.161120.22142/goproxy/httpproxy.(*Handler).ServeHTTP(0x1111a440, 0x
a313a0, 0x1f09ddd0, 0x12672200)
        <autogenerated>:1 +0x56
net/http.serverHandler.ServeHTTP(0x114aa100, 0xa313a0, 0x1f09ddd0, 0x12672200)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2558 +0x70
net/http.(*conn).serve(0x1884e360, 0xa31b20, 0x118c7f60)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:1815 +0x578
created by net/http.(*Server).Serve
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2658 +0x225

goroutine 21616 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xa5f7f8)
        /tmp/goproxy.161120.22142/go/src/runtime/sema.go:62 +0x29
sync.(*Mutex).Lock(0xa5f7f4)
        /tmp/goproxy.161120.22142/go/src/sync/mutex.go:87 +0xbc
github.com/phuslu/glog.(*loggingT).output(0xa5f7e0, 0x0, 0x268885a0, 0xa2383a, 0
x6, 0x23b, 0x0)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:672
+0x2e
github.com/phuslu/glog.(*loggingT).printf(0xa5f7e0, 0x0, 0x85a892, 0x1a, 0x1912f
b1c, 0x7, 0x7)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:655
+0xf7
github.com/phuslu/glog.Verbose.Infof(0x7dfa01, 0x85a892, 0x1a, 0x1912fb1c, 0x7,
0x7)
        /tmp/goproxy.161120.22142/gopath/src/github.com/phuslu/glog/glog.go:1063
 +0x60
_/tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae.(*Filter).RoundTrip(0x1
12ea500, 0xa31be0, 0x18aa6ce0, 0x13786400, 0xa31be0, 0x18aa6ce0, 0x0, 0x0, 0x0)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/filters/gae/gae.go:571 +0xa2
8
_/tmp/goproxy.161120.22142/goproxy/httpproxy.Handler.ServeHTTP(0xa31ae0, 0x1111a
100, 0x112fa7e0, 0x3, 0x4, 0x112fa800, 0x3, 0x4, 0x11120070, 0x1, ...)
        /tmp/goproxy.161120.22142/goproxy/httpproxy/handler.go:89 +0x41c
_/tmp/goproxy.161120.22142/goproxy/httpproxy.(*Handler).ServeHTTP(0x1111a440, 0x
a313a0, 0x169666c0, 0x146f6500)
        <autogenerated>:1 +0x56
net/http.serverHandler.ServeHTTP(0x114aa100, 0xa313a0, 0x169666c0, 0x146f6500)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2558 +0x70
net/http.(*conn).serve(0x14f35e60, 0xa31b20, 0x15553760)
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:1815 +0x578
created by net/http.(*Server).Serve
        /tmp/goproxy.161120.22142/go/src/net/http/server.go:2658 +0x225

goroutine 151392 [semacquire, 5 minutes]:

**Comment by phuslu** [comment]
能把日志重新格式化贴下吗，这样看不清。

**Comment by inkdie** [comment]
稍等，我用word尝试整理一下日志。

**Comment by inkdie** [comment]
整理很麻烦，我用邮箱给你发截图吧

**Comment by inkdie** [comment]
邮件已发送，很幸运，两种状态都迅速复现并截图了。

**Comment by phuslu** [comment]
最新版也有这样的问题吗？

**Comment by inkdie** [comment]
我版本号跟的很紧，现在是1137，我看您1138只修改了readme才没跟进。

**Comment by johnsonz** [comment]
个人ID-3.appspot.com:443 

原来支持中文的啊

**Comment by yaoguaishou** [comment]
iphone真蛋疼,发短信看视频连接pac都能死机
