### ISSUE TITLE
服务器端upload失败

### ISSUE THREAD

**Issue by zzgpku** [phuslu/goproxy#1330]
===============================================================
 GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备
。
APPID:zzggoproxy1
10:34 PM Application: zzggoproxy1
10:34 PM Host: appengine.google.com
10:34 PM Rolling back the update.
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\uplo
ader.py", line 132, in <module>
    main()
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\uplo
ader.py", line 118, in main
    upload('gae', appid)
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\uplo
ader.py", line 102, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 2951, in Run
    self.action(self)
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 5044, in __call__
    return method()
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 4397, in Rollback
    self._Rollback()
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 4442, in _Rollback
    appversion.Rollback(force_rollback)
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 2362, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "D:\系统文件夹\Desktop\phuslu-goproxy-88eb0fc\phuslu-goproxy-88eb0fc\goog
le_appengine\google\appengine\tools\appcfg.py", line 1696, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line
 247, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "google_appengine\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060]
请按任意键继续. . .
求问怎么破？

**Comment by jzp820927** [comment]
不明觉厉，不行，就用XX部署。

**Comment by zzgpku** [comment]
@jzp820927 XX部署的goproxy也能用？我以为xx部署的只能xx或goagent用

**Comment by jzp820927** [comment]
都可以，XX的通用所有平台，只不过 GOProxy 自己的服务端，是给自己量身打造的，性能要好些而已。其实差别也不大，主要决定因素还在IP

**Comment by phuslu** [comment]
非常不推荐使用 GoAgent/XX-Net 的 python 客户端。

1. 和 goproxy 客户端的抗干扰策略不匹配，效果很不好。
2. python 版本的效率也不高。

**Comment by wenliyang** [comment]
解压文件夹换个再试，比如

d:\phuslu-goproxy-88eb0fc\

**Comment by Pekary** [comment]
用XX上传出错.
Error 400: --- begin server output ---
Error when loading application configuration:
'utf8' codec can't decode byte #x8f: unexpected code byte
  in "<string>", position 1
--- end server output ---

**Comment by SeaHOH** [comment]
社长的服务端效率高，配合满分，还是不要用 py 服务端的好。

**Comment by zzgpku** [comment]
@phuslu 那我该怎么弄？上传一直失败，我特意新注册的appid

**Comment by zzgpku** [comment]
@wenliyang 没有用啊，我弄到C盘根目录也一样。

**Comment by SeaHOH** [comment]
弹浏览器认证页面出来没有？

**Comment by phuslu** [comment]
@zzgpku 实在不行，用 vps 上传。

**Comment by zzgpku** [comment]
@phuslu xxnet日志显示[WARNING] server app return fail, status:502

**Comment by phuslu** [comment]
@zzgpku vps 上传。

**Comment by zzgpku** [comment]
@phuslu 没有vps，用的免费的ss仍然失败。

**Comment by phuslu** [comment]
ss 是 socks5 代理，暂不支持。

我觉得你可以先放弃使用 goproxy 服务端了，后续可以关注这个贴子的进展。

https://github.com/phuslu/goproxy/issues/1149

**Comment by phuslu** [comment]
@zzgpku 请见 https://github.com/phuslu/goproxy/issues/1149#issuecomment-263051699
