### ISSUE TITLE
goagent  出错。  求指点。。。

### ISSUE THREAD

**Issue by judyonlyvv** [phuslu/goproxy#151]
加载一点就出现错误。求指点。

SystemError: (libev) select: Unknown error
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "proxy.py", line 1670, in <module>
    main()
  File "proxy.py", line 1665, in main
    gae_server.serve_forever()
  File "E:\goagent3.2.3\goagent-goagent-985cbd5\local\python27.zip\SocketServer.
py", line 236, in serve_forever
  File "E:\goagent3.2.3\goagent-goagent-985cbd5\local\python27.zip\SocketServer.
py", line 155, in _eintr_retry
  File "E:\goagent3.2.3\goagent-goagent-985cbd5\local\packages.egg\win32\gevent\
select.py", line 68, in select
  File "E:\goagent3.2.3\goagent-goagent-985cbd5\local\packages.egg\win32\gevent\
event.py", line 77, in wait
  File "E:\goagent3.2.3\goagent-goagent-985cbd5\local\packages.egg\win32\gevent\
hub.py", line 331, in switch
SystemError: (libev) select: Unknown error

**Comment by xyuanmu** [comment]
检查一下proxy.ini等号后有没有留一个空格。

**Comment by judyonlyvv** [comment]
都有啊。  昨天用的好好的。  今天就这样。  真是奇怪

**Comment by wangbingqian** [comment]
Mac用户？
