### ISSUE TITLE
GOAgent问题

### ISSUE THREAD

**Issue by gosex** [phuslu/goproxy#1563]
GOA 3.2.3上 twitter 转贴，点赞不能用，之前还可用，不知道能解决不？
问题如下
 
WARNING - [Mar 19 14:24:09] create_ssl_connection to 'api.twitter.com' with [('199.59.148.208', 443), ('199.59.148.208', 443)] return ['timed out'], try again.
ERROR - [Mar 19 14:24:09] create_http_request "OPTIONS https://api.twitter.com/1.1/favorites/create.json" failed:timed out
Traceback (most recent call last):
  File "goagent\local\proxylib.py", line 2078, in create_http_request
  File "goagent\local\proxylib.py", line 2057, in create_ssl_connection
timeout: timed out

**Comment by SeaHOH** [comment]
OPTIONS 这个 GAE 没办法，你配置成走 vps 应该就可以了。

**Comment by phuslu** [comment]
用 goproxy 的话， options 请求还好。已经能做支持了 https://github.com/phuslu/goproxy/blob/master/httpproxy/filters/gae/gae.json#L88-L98

goagent 的话，没法再继续维护了。

**Comment by SeaHOH** [comment]
请问，这个 FakeOptions 有没有什么限制呢？

**Comment by caofengzi** [comment]
現在用goagent就是下載大東西的時候用，瀏覽網站goa的確沒有gop快，希望老大儘快把gop的autorange弄好。

**Comment by blob2015** [comment]
@caofengzi @phuslu 
这个未必与autorange相关？autorange好像对于文件（后缀名）有很多限制。
主要还是社长对于下载的需求太少 😀

**Comment by phuslu** [comment]
FakeOptions 属于锦上添花的东东。目前测试下来，能搞定 twitter 系网站和 facebook 的图片上传。

更多适用网站还需更多测试。

**Comment by jasonliul** [comment]
@caofengzi 
这很奇怪.... Goproxy在俺这里几乎总是满速. 旧版goagent并不更快.

**Comment by caofengzi** [comment]
@jasonliul 俺說的是下載超過32m大文件，瀏覽網站還是gp快。

**Comment by jasonliul** [comment]
@caofengzi 
这个32M的说法一直很奇怪, 俺木有遇见. 
有些网站限制gae下载, 这是有的.

俺推测是用了中国谷歌ip的原因. 现在国外Gip随机丢包, 因此可能下载会受影响.

**Comment by SeaHOH** [comment]
应该是网址文件本身不支持 range，且大小超过 32MB。

**Comment by caofengzi** [comment]
比如下載voa的視頻超過32m就提示沒有發現文件鏈接，小於32m的就可以下載。但是goa沒有這個情況。

**Comment by SeaHOH** [comment]
视频一般是支持 range 的，不过我没用 goproxy，不知道为什么，有没有人来测试一下。

**Comment by gosex** [comment]
哎，看来只能换个翻墻了

**Comment by gosex** [comment]
@SeaHOH 
开启 vps ，一样没用

**Comment by SeaHOH** [comment]
@gosex 
我觉得你可能配置写错了，能不能贴来看下。

**Comment by gosex** [comment]
@SeaHOH 
vps配置用的是默认的 ：） 
其他的不懂

**Comment by SeaHOH** [comment]
默认是没有 vps 的，需要自己部署。
部署好了在 [proxy] 小节进行配置；
然后在 [hosts] 小节配置 
```ini
.twitter.com = 
```

**Comment by mikecheng78** [comment]
下载视频我用goa，使用VDOWN设置goa代理后，下载速度可以达到1M/S-3M/S,但是 vdown软件没有代理 gop的选项。
