### ISSUE TITLE
奇怪今天用r1342打开.youtube出现乱码其他网页都正常，用XX-Net打开youtube又是正常的。

### ISSUE THREAD

**Issue by jap33** [phuslu/goproxy#1594]
![default](https://cloud.githubusercontent.com/assets/15140842/24488065/daebc5d4-1546-11e7-9220-b5bba357b5e9.PNG)
(如果您是遇到 goproxy 使用问题而并不清楚具体原因的话，请尽量提供更多信息，比如平台，日志截图，浏览器截图等。否则问题可能会被忽略或关闭)

**Comment by lucifercn** [comment]
嗯 好像同样问题啊  然后我换谷歌浏览器就没问题了。。。

**Comment by jasonliul** [comment]
换成其他代理也正常

**Comment by phuslu** [comment]
可能是 goproxy 的 GAE 自动探测编码的逻辑出 bug 了(本来这段逻辑是为了修复 GAE 访问百度百科乱码）。

我看下。

**Comment by jap33** [comment]
今天只有gop打开youtube乱码，其他hosts直连、ss和XX-Net都正常。[同一火狐浏览器]。

**Comment by CongZeng** [comment]
乱码是怎么回事？

**Comment by jasonliul** [comment]
@jap33 
教授, 色长需要时间, 急什么...

**Comment by phuslu** [comment]
在上班呢，晚上回去看。

**Comment by jasonliul** [comment]
@phuslu
社长, jap33教授起码有300纸飞机节点.
特意嚎叫凑凑人气而已.

社长安心上班泡女同事即可.

**Comment by phuslu** [comment]
奇怪我这边并不能复现。不过尝试回滚了 server.gae 的改动。

可以尝试部署一下最新 server.gae 试试 https://github.com/phuslu/goproxy/archive/server.gae.zip

**Comment by hotbbs** [comment]
![image](https://cloud.githubusercontent.com/assets/12554843/24502956/9f6b2c84-1582-11e7-8df7-612681de44ce.png)
更新服务端出现错误，求助！

**Comment by Kisesy** [comment]
大概是 youtube, 默认优先编码为 br 的原因？
content-encoding:br
其实现在大部分浏览器并不会解压br,也不会发送br头, 但是 gae 默认是自动发送的
可以用 gop 访问 https://http2.golang.org/reqinfo 可以看到发送了两次 Accept-Encoding
Accept-Encoding: gzip, deflate, sdch
Accept-Encoding: gzip,deflate,br

**Comment by hotbbs** [comment]
部署新的server，还是不能解决乱码的问题

**Comment by phuslu** [comment]
@Kisesy 谢谢提供线索，我看下。

**Comment by phuslu** [comment]
非常感谢。我在 r1345 尝试做了修复。

另外 GAE 服务端推荐也更新一下。

**Comment by Kisesy** [comment]
我这里感觉好像可以了...

**Comment by jasonliul** [comment]
Loading Google Appengine SDK...
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Temp\goproxy-r56\uploader.py", line 111, in <module>
    from google_appengine.google.appengine.tools import appcfg
  File "D:\Temp\goproxy-r56\google_appengine\google\appengine\tools\appcfg.py",
line 79, in <module>
    from google.appengine.tools import bulkloader
  File "google_appengine\google\appengine\tools\bulkloader.py", line 125, in <mo
dule>
    from google.appengine.ext.remote_api import remote_api_stub
  File "google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", li
ne 93, in <module>
    from google.appengine.ext.remote_api import remote_api_services
  File "google_appengine\google\appengine\ext\remote_api\remote_api_services.py"
, line 42, in <module>
    from google.appengine.api.search import search_service_pb
  File "google_appengine\google\appengine\api\search\__init__.py", line 23, in <
module>
    from search import AtomField
  File "google_appengine\google\appengine\api\search\search.py", line 58, in <mo
dule>
    from google.appengine.api.search import expression_parser
  File "google_appengine\google\appengine\api\search\expression_parser.py", line
 28, in <module>
    from google.appengine.api.search import unicode_util
ImportError: cannot import name unicode_util
请按任意键继续. . .

服务端不能运行, 奇怪

**Comment by phuslu** [comment]
啊，有点奇怪。我还没有复现出来。。。

**Comment by jasonliul** [comment]
@phuslu 
把老版goagent 的三个python27.* 拷贝过来
显示竟然又不同
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Temp\goproxy-r56\uploader.py", line 98, in <module>
    import httplib2
  File "google_appengine\httplib2\__init__.py", line 29, in <module>
    import email
ImportError: No module named email
请按任意键继续. . .

**Comment by Kisesy** [comment]
[google_appengine.tar.gz](https://github.com/phuslu/goproxy/files/882577/google_appengine.tar.gz)

好像是有问题, 缺了几个文件, 我传一份补好的吧

**Comment by jasonliul** [comment]
@Kisesy 

主任, 这下可以了.

**Comment by phuslu** [comment]
啊，的确是缺文件了。git add --all . 居然出 bug 了。

现在已经补上...

**Comment by 2378** [comment]
同上 
双边升级后 正常

**Comment by blob2015** [comment]
社长、主任威武，俺这边服务端与客户端都没有升级，看yt好像也没事，继续先用着？

**Comment by wpyok500** [comment]
r1343表示正常，r51服务端
![default](https://cloud.githubusercontent.com/assets/14154547/24531014/6db762d2-15e8-11e7-8f51-1a1c983605b9.png)

**Comment by Kisesy** [comment]
只要浏览器升级到新版，支持了 br 或者直接把 youtube 设置成 googlehk 直连，不升级也是没有这个问题

**Comment by jasonliul** [comment]
@Kisesy 
肿么设置? 主任

**Comment by Kisesy** [comment]
@jasonliul 
打开 gae.json, 找 SiteToAlias, 去掉 // "*.youtube.com": "google_hk",  的注释, 或者把这个加到 user.json 里

**Comment by jasonliul** [comment]
@Kisesy 
果然, 测试
https://youtu.be/ebXbLfLACGM?list=LLQ4xGnSfjNiFJ4NfH1cDySA

**Comment by Kisesy** [comment]
@jasonliul 
googlevideo.com 也是可直连的，不过会对应IP，编码很复杂，gip 没法通用，如果能通用，那真是妙不可言

**Comment by jasonliul** [comment]
@Kisesy 
Goproxy 其实一直很平稳, 不像goagent不时还要好好学习, 天天向上.

不过脱离了翻墙色彩, 就没有那么多怪咖, 时时折腾新花样了. 那些翻墙网站什么的, 好像放弃了狗鞭.

**Comment by phuslu** [comment]
挺好的，在现在风声鹤唳草木皆兵的形式下，能够一直偏安一隅也算是造化呢。

**Comment by jasonliul** [comment]
@phuslu 
社长也玩"结庐在人境"? 多了许多咖啡时间, 这样反倒好. :)

**Comment by kirbyzhu** [comment]
敲敲的进村 打枪的不要

**Comment by cryyifei** [comment]
@Kisesy 请问goagent V3.2.3怎么设置

**Comment by Kisesy** [comment]
@cryyifei 
在proxy.ini 或者 proxy.user.ini 里的 [profile] 下面添加 `.youtube.com = google_hk` 注意前面有个 .

**Comment by Kisesy** [comment]
![s8rg20a006gjuq](https://cloud.githubusercontent.com/assets/5843694/24548224/b153d67a-1646-11e7-84f0-0e101199450c.gif)

感受宁静

**Comment by cryyifei** [comment]
@Kisesy 现在又出现隐私设置错误，你的连接不是私密。

**Comment by jasonliul** [comment]
@Kisesy 
含饴弄孙, 髀肉横生. 
:)

**Comment by phuslu** [comment]
请再次更新服务端和服务端，用一个比较高效的方式修好了，比之前有性能提升。

**Comment by zhaipeng** [comment]
用goagent   3.2.3也出现这个问题。请问怎么修复？
