### ISSUE TITLE
上传最新服务端出现如下错误

### ISSUE THREAD

**Issue by hotbbs** [phuslu/goproxy#1598]
![image](https://cloud.githubusercontent.com/assets/12554843/24503558/284bc142-1585-11e7-8b60-775d70df182d.png)
上传 了最新的服务端，但出现几次这样的错误，但重新多试一次上传，也可能正常了，感觉很奇怪。

**Comment by hotbbs** [comment]
![image](https://cloud.githubusercontent.com/assets/12554843/24503742/f6894bce-1585-11e7-94b9-29a809a198e5.png)
再出错一次

**Comment by hotbbs** [comment]
经过半个小时的奋战，终于传好了17个appid，哈哈

**Comment by phuslu** [comment]
惭愧，google appengine sdk 又有改动。

我又同步了一次，现在最新的 server.gae (r54) 应该成功率较高了。

**Comment by hotbbs** [comment]
r54 打开直接就报错了

**Comment by kirbyzhu** [comment]
我也是 打开就报错

**Comment by kirbyzhu** [comment]
另外现在github贴图经常出问题 好奇怪

**Comment by kirbyzhu** [comment]
r56也是打开就报错

**Comment by kirbyzhu** [comment]
@phuslu 

Loading Google Appengine SDK...
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\software\2014google\goproxy\goproxy-r56\uploader.py", line 111, in <module>
    from google_appengine.google.appengine.tools import appcfg
  File "D:\software\2014google\goproxy\goproxy-r56\google_appengine\google\appengine\tools\appcfg.py", line 79, in <module>
    from google.appengine.tools import bulkloader
  File "google_appengine\google\appengine\tools\bulkloader.py", line 125, in <module>
    from google.appengine.ext.remote_api import remote_api_stub
  File "google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 93, in <module>
    from google.appengine.ext.remote_api import remote_api_services
  File "google_appengine\google\appengine\ext\remote_api\remote_api_services.py", line 42, in <module>
    from google.appengine.api.search import search_service_pb
  File "google_appengine\google\appengine\api\search\__init__.py", line 23, in <module>
    from search import AtomField
  File "google_appengine\google\appengine\api\search\search.py", line 58, in <module>
    from google.appengine.api.search import expression_parser
  File "google_appengine\google\appengine\api\search\expression_parser.py", line 28, in <module>
    from google.appengine.api.search import unicode_util
ImportError: cannot import name unicode_util
请按任意键继续. . .

**Comment by cnrip** [comment]
R54直接报错.

Loading Google Appengine SDK...
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\phuslu-goproxy\uploader.py", line 111, in <module>
    from google_appengine.google.appengine.tools import appcfg
  File "D:\phuslu-goproxy\google_appengine\google\appengine\tools\appcfg.py", line 79, in <module>
    from google.appengine.tools import bulkloader
  File "google_appengine\google\appengine\tools\bulkloader.py", line 125, in <module>
    from google.appengine.ext.remote_api import remote_api_stub
  File "google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 93, in <module>
    from google.appengine.ext.remote_api import remote_api_services
  File "google_appengine\google\appengine\ext\remote_api\remote_api_services.py", line 42, in <module>
    from google.appengine.api.search import search_service_pb
  File "google_appengine\google\appengine\api\search\__init__.py", line 23, in <module>
    from search import AtomField
  File "google_appengine\google\appengine\api\search\search.py", line 58, in <module>
    from google.appengine.api.search import expression_parser
  File "google_appengine\google\appengine\api\search\expression_parser.py", line 28, in <module>
    from google.appengine.api.search import unicode_util
ImportError: cannot import name unicode_util
请按任意键继续. . .

**Comment by phuslu** [comment]
r57 修复了

**Comment by fredericky123** [comment]
r57还是有问题
![1](https://cloud.githubusercontent.com/assets/13982749/24513939/2db66590-15a5-11e7-8f15-9365a299d1c1.PNG)

**Comment by jap33** [comment]
r57还是有问题

**Comment by jzmswe** [comment]
换google_hk IP，每次只要我换新鲜热乎的IP，都是一次成功。另：R57同样如此。

**Comment by kirbyzhu** [comment]
更新之后有点小bug @phuslu 
shell的显示界面一旦拉宽 焦点就没了


![default](https://cloud.githubusercontent.com/assets/10296293/24533918/4b285dce-15fd-11e7-84ab-99e04cab91dd.png)

**Comment by wangbingqian** [comment]
@phuslu 
R51需要更新吗？怎么判断是否需要更新？

**Comment by phuslu** [comment]
请再次更新服务端和服务端，用一个比较高效的方式修好了，比之前有性能提升。

**Comment by mouseroser** [comment]
我用R60一开始也是失败，后来把goproxy升级到最新版本，关掉所有的web浏览器，重新用administrator打开goproxy后再上传server端，一气呵成！！！

**Comment by jzmswe** [comment]
几次失败，用DNS一键优化换了个最快DNS。重新上传，一气呵成。

**Comment by mouseroser** [comment]
我是直接在网件的无线路由里面把DNS设成：114.114.114.114和114.114.115.115。你也可以设置成8.8.8.8

2017-04-04 14:21 GMT+08:00 jzmswe <notifications@github.com>:

**Comment by jzmswe** [comment]
114盗取用户隐私，Google DNS因为干扰，很不稳定。

**Comment by fredericky123** [comment]
@jzmswe 直接再gae.user配置dns就好吧？可是ipconfig /all显示的是运营商的地址，如何确定自己配置的dns被使用了呢

**Comment by jzmswe** [comment]
@fredericky123 DNS一键优化，自动更换系统DNS，gae.user.json里的DNS，自己手动更换。更换后，也不可能会与ipconfig/all显示的DNS有任何关系。
