### ISSUE TITLE
通过 GAE r58 上传时授权无法接收

### ISSUE THREAD

**Issue by SeaHOH** [phuslu/goproxy#1607]
`accounts.google.com` 走 GAE，httplib2 无法解码。
```
  --noauth_local_webserver

Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "S:\goproxy-r58\uploader.py", line 151, in <module>
    main()
  File "S:\goproxy-r58\uploader.py", line 137, in main
    upload('gae', appid)
  File "S:\goproxy-r58\uploader.py", line 121, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 5514, in main
    result = AppCfgApp(argv).Run()
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 2977, in Run
    self.action(self)
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 5170, in __call__
    return method()
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 4523, in Rollback
    self._Rollback()
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 4568, in _Rollback
    appversion.Rollback(force_rollback)
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 2387, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "S:\goproxy-r58\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 240, in Send
    self._Authenticate(self.http, auth_errors[0] > 0)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 465, in _Authenticate
    self.credentials = tools.run_flow(flow, self.storage, self.flags)
  File "google_appengine\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "google_appengine\oauth2client\tools.py", line 225, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "google_appengine\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "google_appengine\oauth2client\client.py", line 2000, in step2_exchange
    headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cacheke
)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "google_appengine\httplib2\__init__.py", line 1318, in _conn_request
    content = _decompressContent(response, content)
  File "google_appengine\httplib2\__init__.py", line 393, in _decompressContent
    content = zlib.decompress(content)
zlib.error: Error -3 while decompressing data: incorrect header check
请按任意键继续. . .
```

**Comment by phuslu** [comment]
哦，这是 httplib2 的已知bug， 我顺手改了。
https://github.com/phuslu/goproxy/commit/aff087d3042a2fb13e88dbcc3382865addbdeb6e

可以用改动的这个关键字 google 下，网上已经讨论的很充分了.

**Comment by phuslu** [comment]
提了一个 PR 给 httplib2，https://github.com/jcgregorio/httplib2/pull/334

**Comment by SeaHOH** [comment]
原来如此，我还以为是服务端导致的。

**Comment by phuslu** [comment]
httplib2 的 PR 已经合并了，终于修掉了。。。

**Comment by SeaHOH** [comment]
社长威武，哈哈。
这些人为啥不自己修复，这么古老的 bug。

**Comment by phuslu** [comment]
主要还是 deflate 比较古老用的较少的缘故。

1. deflate 压缩后体积比 gzip 小一点，但是实现一般都不支持流压缩。
2. gzip 的实现一般都支持流压缩。

所以在 chunked 编码的情形下 gzip 优势比较大。

不过 GAE 情形比较特殊
1. 不支持返回流压缩的回应
2. 网络不稳定的现状下，体积比较重要，可以用寸土寸金来形容。

所以就选择 deflate

**Comment by SeaHOH** [comment]
又想了下：
GAE 本身是不支持 chunked，但是我们的响应是包装在里面的，不是直接使用它的头部。
我觉得还是有办法实现，自己写方法把 gzip 流转为 chunked，只要最终大小不超过 GAE 限制。

**Comment by phuslu** [comment]
考虑过，但是始终没有找到很好的办法。。。

**Comment by SeaHOH** [comment]
请问是那个环节有问题，不知道我能不能一起想下办法。

**Comment by phuslu** [comment]
我的考虑是，

如果通过增加 RTT (RoundTrip Time) 来实现模拟 chunked，是得不偿失的。
那么限定在 1-RTT 来模拟 chunked, 基于 GAE 的接口，我又没找到可能性。

**Comment by SeaHOH** [comment]
我刚才看了下服务端源码
最后返回时，resp.Body 没有什么特别处理，只是单纯的 iocopy；
那么把 resp.Body.Read 替换为模拟 chunked 的返回不就可以了？或许还需要个中间缓存之类的？
另外模拟 chunked 还需要单开个线程？

**Comment by phuslu** [comment]
不是，chunked 的限制在更底层。试下就知道了。。。

**Comment by SeaHOH** [comment]
我大概明白你的意思了，但 chunked 不就是必要时要多次接收么，链接不断开就行。
性能上，限制一下大小，超过多少才用 chunked，其它还是 deflate。

**Comment by phuslu** [comment]
额，强行实现实现的话，要增加 rtt ， 我觉得不靠谱。

**Comment by SeaHOH** [comment]
我也就是这么提议下，这样社长就会在心头考虑，说不定那天就想到好办法了。 :laughing:

**Comment by phuslu** [comment]
哎，谢谢。gae 限制比较多，只能尽人事而安天命了。
