### ISSUE TITLE
奇怪的提示，晕圈了

### ISSUE THREAD

**Issue by maryjeck** [phuslu/goproxy#1817]
2017/06/22 22:18:54 http: panic serving 127.0.0.1:53749: runtime error: invalid memory address or nil pointer dereference
goroutine 1796 [running]:
net/http.(*conn).serve.func1(0xc04335c1e0)
        /tmp/goproxy.170621.25670/go/src/net/http/server.go:1693 +0xd7
panic(0x9d15c0, 0xdc1aa0)
        /tmp/goproxy.170621.25670/go/src/runtime/panic.go:491 +0x291
github.com/phuslu/quic-go/h2quic.(*client).wrapError(0xc0420a09a0, 0xd4d080, 0xc0431a4d80, 0x13)
        /tmp/goproxy.170621.25670/gopath/src/github.com/phuslu/quic-go/h2quic/client.go:143 +0x60
github.com/phuslu/quic-go/h2quic.(*client).RoundTrip(0xc0420a09a0, 0xc042289100, 0x13, 0xd4d040, 0xc0420a09a0)
        /tmp/goproxy.170621.25670/gopath/src/github.com/phuslu/quic-go/h2quic/client.go:165 +0xca9
github.com/phuslu/quic-go/h2quic.(*QuicRoundTripper).RoundTrip(0xc0420ed2f0, 0xc042289100, 0x443f00, 0xc0430e4f98, 0x52b94a)
        /tmp/goproxy.170621.25670/gopath/src/github.com/phuslu/quic-go/h2quic/roundtrip.go:86 +0x45d
_/tmp/goproxy.170621.25670/goproxy/httpproxy/filters/gae.(*QuicTransport).RoundTrip(0xc0420026a0, 0xc042289100, 0xc0420026a0, 0x1, 0x1)
        /tmp/goproxy.170621.25670/goproxy/httpproxy/filters/gae/quictransport.go:26 +0x91
_/tmp/goproxy.170621.25670/goproxy/httpproxy/filters/gae.(*Filter).RoundTrip(0xc042494800, 0xd54c00, 0xc04328c930, 0xc042289100, 0xd54c00, 0xc04328c930, 0x0, 0x0, 0x0)
        /tmp/goproxy.170621.25670/goproxy/httpproxy/filters/gae/gae.go:537 +0x847
_/tmp/goproxy.170621.25670/goproxy/httpproxy.Handler.ServeHTTP(0xd54b00, 0xc042480050, 0xc042031300, 0x3, 0x4, 0xc042031340, 0x3, 0x4, 0xc04225ff00, 0x1, ...)
        /tmp/goproxy.170621.25670/goproxy/httpproxy/handler.go:89 +0xe50
_/tmp/goproxy.170621.25670/goproxy/httpproxy.(*Handler).ServeHTTP(0xc04228e930, 0xd54400, 0xc04334a0e0, 0xc042288c00)
        <autogenerated>:1 +0x9b
net/http.serverHandler.ServeHTTP(0xc042067110, 0xd54400, 0xc04334a0e0, 0xc042288c00)
        /tmp/goproxy.170621.25670/go/src/net/http/server.go:2610 +0xbb
net/http.(*conn).serve(0xc04335c1e0, 0xd54b40, 0xc0422ea380)
        /tmp/goproxy.170621.25670/go/src/net/http/server.go:1797 +0x724
created by net/http.(*Server).Serve
        /tmp/goproxy.170621.25670/go/src/net/http/server.go:2711 +0x28f
I0622 22:18:56.382653    9068 gae.go:611] 127.0.0.1:52757 "GAE DIRECT GET https://0.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=gmail&appver=chat_frontend_20170612.08_p0&gsessionid=2WhqeHlUwtstQI2ZDDEbcE4_JGgjsz5c&VER=8&RID=rpc&SID=D15D3E501C992834&CI=1&AID=70&TYPE=xmlhttp&zx=nkakgaqv4one&t=1 HTTP/1.1" 200

**Comment by Kisesy** [comment]
https://github.com/phuslu/goproxy/issues/1810#issuecomment-310124756

**Comment by phuslu** [comment]
使用 quic 的同学稍安吧，刚刚引入这东东。稳定需要一段时间，短则一周，迟则一个月。我会把 quic 搞搞稳定哒。

**Comment by jasonliul** [comment]
@phuslu 
社长最近经常坐台, 让我等酒保没事可做~~
LOL

**Comment by yDan** [comment]
怎有使用quic？有没有教程呢？

**Comment by yDan** [comment]
怎样使用quic？有没有教程呢？

**Comment by phuslu** [comment]
下载最新版，打开 gae.json 里面的 EnableQuic 即可。

**Comment by yDan** [comment]
最新版的链接现在都看不到了，社长把它弄去哪里了？

**Comment by qwerttaa** [comment]
https://github.com/phuslu/goproxy-ci/releases

这儿呢

**Comment by zdf0145** [comment]
我也出现了同样的情况，重新载入后又好了

**Comment by blob2015** [comment]
俺这里，下午出现好几次了 😀
