### ISSUE TITLE
最近运行get-latest-goproxy.cmd检测不到新版了，不知为何。

### ISSUE THREAD

**Issue by gthbshen** [phuslu/goproxy#1972]
如题。明明是网上已经有新版本了，但get-latest-goproxy.cmd总说版本已经最新。
手动更新到了最新的 r1558版，再运行这个脚本，则提示说：
0. Local GoProxy version r1558
1. Checking GoProxy Version
Cannot detect goproxy_windows_amd64 version

**Comment by gthbshen** [comment]
发觉r1557版以上都不能翻墙，出错提示：
{
    "type": "appengine",
    "host": "xxxxxxxxx.appspot.com",
    "software": "Google App Engine/1.9.48",
    "error": "urlfetch password required"
}
换回r1556版以下又正常了。

**Comment by phuslu** [comment]
服务端和客户端目前都需要升级。等我发帖通知吧。

**Comment by gthbshen** [comment]
好，谢站长。

**Comment by gthbshen** [comment]
用了最新的gae-r83，uploader.bat时总是出错，升不了：

Traceback (most recent call last):
  File "uploader.py", line 151, in <module>
  File "uploader.py", line 144, in main
  File "uploader.py", line 112, in upload
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 5514, in main
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 2977, in Run
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 5170, in __call__
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 4523, in Rollback
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 4568, in _Rollback
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 2387, in Rollback
  File "d:\Programs\Proxy\goproxy\goproxy-gae-r83\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 240, in Send
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 465, in _Authenticate
  File "google_appengine\oauth2client\util.py", line 137, in positional_wrapper
  File "google_appengine\oauth2client\tools.py", line 227, in run_flow
SystemExit: Authentication has failed: Invalid response: 415.

**Comment by phuslu** [comment]
发新版了 https://github.com/phuslu/goproxy/issues/1033

**Comment by gthbshen** [comment]
客户端和服务端同时更新，终于好了，感谢社长！
