### ISSUE TITLE
这是什么错误：NewConfig("gae.json") failed: invalid character '"' after array element

### ISSUE THREAD

**Issue by boromeke** [phuslu/goproxy#242]
尝试部署下，结果不成功，哪位大神知道下面是什么错误，如何解决？
THX！！

ERROR: logging before flag.Parse: F1011 23:49:13.827756    2221 gae.go:33] NewConfig("gae.json") failed: invalid character '"' after array element
goroutine 1 [running, locked to thread]:
github.com/golang/glog.stacks(0x80bc00, 0x0, 0x0, 0x0)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x7e6da0, 0xc800000003, 0xc8200c0240, 0x7a0cf1, 0x6, 0x21, 0x0)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:720 +0x2b8
github.com/golang/glog.(*loggingT).printf(0x7e6da0, 0x3, 0x5c19c0, 0x19, 0xc82003dee8, 0x2, 0x2)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0x5c19c0, 0x19, 0xc82003dee8, 0x2, 0x2)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:1148 +0x5d
github.com/phuslu/goproxy/httpproxy/filters/gae.init.1()
	/home/phuslu/go1.5/gopath/src/github.com/phuslu/goproxy/httpproxy/filters/gae/gae.go:33 +0x223
github.com/phuslu/goproxy/httpproxy/filters/gae.init()
	/home/phuslu/go1.5/gopath/src/github.com/phuslu/goproxy/httpproxy/filters/gae/gae.go:165 +0x153
main.init()
	/home/phuslu/go1.5/gopath/src/github.com/phuslu/goproxy/goproxy/main.go:268 +0xb7

**Comment by johnsonz** [comment]
非法字符

**Comment by xyuanmu** [comment]
看看是不是用了全角符号了，改成半角，如引号和逗号

**Comment by boromeke** [comment]
里面的字符""我没动过

**Comment by boromeke** [comment]
@phuslu  这是不是bug? 我下载的是goproxy_darwin_amd64-r169.zip。 这个问题该如何解决。谢谢！

**Comment by HenryChanhy** [comment]
这个是macOS的版本。字符集不对。

**Comment by HenryChanhy** [comment]
darwin。。。。 macOS用的。你下错版本了

**Comment by boromeke** [comment]
@HenryChanhy  你好！我是OS X下使用，可以告诉我那部份的字符集不对么？谢谢！

**Comment by johnsonz** [comment]
改了哪部分，贴出来瞧下，估计是用了中文或者全角字符

**Comment by boromeke** [comment]
@johnsonz 

只是添加自己的appid
	"appids": [
		"xx"
		"xx"
		"x34x"
		"xx123"
	],

**Comment by xyuanmu** [comment]
应该是这样，除了最后一个，其他都需要在引号后添加半角逗号
```json
"appids": [
"xx",
"xx",
"x34x",
"xx123"
],
```

**Comment by boromeke** [comment]
@xyuanmu 谢谢！你的方法解决了我的问题！！
