### ISSUE TITLE
checkgoogleip报错怎么解决啊，大神

### ISSUE THREAD

**Issue by lsnmx** [phuslu/goproxy#256]
D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local>"D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\python27.exe" "D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\checkip.py"
[MainThread]load last result,ok cnt:51780,ok file line:319,error cnt: 22517116
Traceback (most recent call last):
File "python27.py", line 95, in 
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\checkip.py", line 1064, in 
list_ping()
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\checkip.py", line 994, in list_ping
ramdomip_thread = RamdomIP(checkqueue,cacheResult,lastokresult|lasterrorresult)
MemoryError

停止扫描后，重新打开就这样，麻烦了，checkgoogleip作者已经潜水了，只能来这求助了

**Comment by xyuanmu** [comment]
1. 先将ip_tmp开头的三个txt文件移动到其他地方，看能否运行
2. 若能运行，看看这三个文件结尾格式是否有问题，删掉有问题内容

**Comment by lsnmx** [comment]
@xyuanmu 16g内存啊

**Comment by xyuanmu** [comment]
@lsnmx 建议一次别放太多IP段，看日志已经扫了2KW+的IP了，扫描的IP越多，消耗内存就越大。不过16G应该是够的，也许是python语言的原因吧。

**Comment by lsnmx** [comment]
@xyuanmu 我就是横扫亚洲地区除CN外所有IP啊，横扫了3天3夜一退去再重新开始就不行了

**Comment by lsnmx** [comment]
@xyuanmu  换你说的也这个问题 D:\Program Files (x86)\Goagent X\CheckIptools>"D:\Program Files (x86)\Goagent X\CheckIptools\python27.exe" "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py"
[MainThread]load last result,ok cnt:51780,ok file line:0,error cnt: 22517116
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 1064, in <module>
    list_ping()
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 994, in list_ping
    ramdomip_thread = RamdomIP(checkqueue,cacheResult,lastokresult|lasterrorresult)

**Comment by lsnmx** [comment]
D:\Program Files (x86)\Goagent X\CheckIptools>"D:\Program Files (x86)\Goagent X\CheckIptools\python27.exe" "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py"
[MainThread]load last result,ok cnt:51780,ok file line:0,error cnt: 22517116
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 1064, in <module>
    list_ping()
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 994, in list_ping
    ramdomip_thread = RamdomIP(checkqueue,cacheResult,lastokresult|lasterrorresult)
MemoryError

**Comment by xyuanmu** [comment]
我的意思是，先将IP段分段，用CheckIptools统计下googleip.txt里面IP的数量，如1KW左右为一段，再扫，一次扫这么大的IP段，导致内存溢出。

**Comment by lsnmx** [comment]
@xyuanmu 哪样很麻烦啊，我想一次性横扫出来啊，看样子是没办法一性横扫这么多了

**Comment by lsnmx** [comment]
CheckIptools 好像不能自动分1KW左右为一段，手动啊，别虾啊，大神

**Comment by lsnmx** [comment]
@xyuanmu 好像不能自动分1KW左右为一段，手动啊，别虾啊，大神

**Comment by xyuanmu** [comment]
@lsnmx 是不能自动，只能手动删掉一部分。这个估计是python语言的缺陷，之前CNMan在VPS上扫描也是内存溢出，后来才分1KW左右扫描的。

**Comment by lsnmx** [comment]
++python啊，难怪GAE换GO语言的都很少挂了，好吧，谢谢啊我横扫了N次都是这样好麻烦，不过建议CheckIptools扫IP前统计下googleip.txt里面IP的数量，超过1KW就自行分割，如何大神

**Comment by lsnmx** [comment]
@xyuanmu

**Comment by xyuanmu** [comment]
可以，找时间再研究下。

**Comment by xyuanmu** [comment]
@lsnmx  已经可以自动分割，将 googleip-数字.txt 里的IP复制到 googleip.txt 里扫描即可。

**Comment by lsnmx** [comment]
@xyuanmu ip amount over 10000000
ip amount over 20000000
ip amount over 30000000
ip amount over 40000000
ip amount over 50000000
ip amount over 60000000
ip amount over 70000000
ip amount over 80000000
ip amount over 90000000
ip amount over 100000000
ip amount over 110000000
ip amount over 120000000
ip amount over 130000000
ip amount over 140000000
ip amount over 150000000
ip amount over 160000000
ip amount below 170000000 分割出来好像还是不太正确

**Comment by lsnmx** [comment]
@xyuanmu  好吧，显示表达问题，现在统计全是10000000个了，分割功能加上吧大神，要不然超过10000000就会害人的，谢谢了

**Comment by CNMan** [comment]
APNIC IPv4 24小时开机大约得扫一个月:)
我这还剩最后的大概1.4亿日本IP待扫

**Comment by xyuanmu** [comment]
@lsnmx ip amount表示IP总数（累加），每1KW生成一个文件，ip amount below 170000000表示不足1.7亿，共生成17的文件，当然由于是IP段，所以数量在1KW上下。到时候抽空写一个轮流测试googleip-数字..txt的 checkip.py，就不用手动复制了。

**Comment by lsnmx** [comment]
@xyuanmu 大神牛

**Comment by lsnmx** [comment]
@CNMan 开500线程啊，CPU和路由能扛就开1000线程

**Comment by CNMan** [comment]
@lsnmx 我是在VPS上扫，已经开最大1000线程了

**Comment by xyuanmu** [comment]
@lsnmx 已经添加自动逐个扫描googleip-1.txt文件IP段功能，欢迎测试：[checkiptools](https://github.com/xyuanmu/checkiptools)

**Comment by ARwMq9b6** [comment]
谢谢 xyuanmu ！解决了大问题。

**Comment by xyuanmu** [comment]
@ARwMq9b6 @lsnmx 刚发现一个小问题，将1077行```i = item[len(item)-5]``` 改成 ```i = re.findall(r'([0-9]+)',item)[0]``` 因为之前测试分段数量少于10，所以截取的位置有问题，不过这样一来扫描顺序是 1、10、11、12、2、3、4这样了，不过tmp文件夹里的文件都有相应后缀的，中断后删掉扫描过的googleip文件即可。

**Comment by lsnmx** [comment]
@xyuanmu 已经可以扫描分段，googleip-1.txt到googleip-1x.txt时，比如扫了googleip-1.txt希望在googleip-1.txt命名上做个标示，要不然不知道扫到哪个分段了，建议！还有更新了命名规则为001、002、003这样就能按顺序扫描？好像引起服务器监测吧，我看别人这么说，所以都是随机扫描的！

**Comment by lsnmx** [comment]
@xyuanmu 有个一个严重BUG，扫描完googleip-1.txt，到扫googleip-2.txt时关了checkip.bat，重新打开会从googleip-1.txt扫起啊

**Comment by xyuanmu** [comment]
@lsnmx 删掉googleip-1.txt即可，今天更新了建议更新到新版本，不然扫描顺序会出问题。

**Comment by lsnmx** [comment]
@xyuanmu 关键是不知道扫描到哪个，扫描完googleip-1.txt，脚本能不能直接删除了googleip-1.txt

**Comment by xyuanmu** [comment]
@lsnmx 行吧，加一句代码就行了：

**Comment by xyuanmu** [comment]
@lsnmx 行吧，加一句代码就行了，末尾代码中加一句：https://github.com/xyuanmu/checkiptools/commit/529d9162fd78a8c4a90df7ee61b2df61084a4771

**Comment by lsnmx** [comment]
@xyuanmu 修改好麻烦更新一下，准备24小时开机扫，谢谢！

**Comment by xyuanmu** [comment]
@lsnmx 如果第一段已经扫完了，可以在生成IP段后手动删掉001，每次分段都是一样的，之后会从002开始扫起。

**Comment by lsnmx** [comment]
@xyuanmu 看着CMD窗口真不知道啥时候扫完001，脚本不能实现扫完001自动删除哪就没办法了

**Comment by lsnmx** [comment]
@xyuanmu 实机测试跑了亚洲地区除CN外所有IP ，不知道跑到什么时候分到了17个出来，谢谢啊

**Comment by CNMan** [comment]
@xyuanmu 分段感觉弄成256(/24)的整数倍比较好:)

**Comment by xyuanmu** [comment]
@CNMan 也对，毕竟CIDR格式还可用于GoGo Tester，统一CIDR格式好了 :smile:

**Comment by lsnmx** [comment]
@xyuanmu 400线程跑了两天才跑了1000W，看来要慢慢跑亚洲地区除CN外所有IP了，哈哈，1000WIP出来也就10来个能用的IP，服了啊

**Comment by xyuanmu** [comment]
@lsnmx 可用IP越来越少，强扫结果很难预料的。

**Comment by imyhxy** [comment]
可以提供一下亚太地区的ip段吗，下载的ip段格式都不太对呀，整理半天没整理出来

**Comment by xyuanmu** [comment]
@imyhxy 你是哪里下载的，如果是下面这样的格式就用Excel打开，选中第三列，复制出来即可。
```
2.160.0.0	2.175.255.255	2.160.0.0/12	1048576
2.200.0.0	2.215.255.255	2.200.0.0/12	1048576
37.80.0.0	37.95.255.255	37.80.0.0/12	1048576
77.0.0.0	77.15.255.255	77.0.0.0/12		1048576
77.176.0.0	77.191.255.255	77.176.0.0/12	1048576
88.64.0.0	88.79.255.255	88.64.0.0/12	1048576
```

**Comment by imyhxy** [comment]
现在换成了1.0的分支，可以用了，不过楼主这个由扫描数量的限制吗？我想先用服务器把所有有证书的ip扫出来，再在本地扫，记得原版是有限制的，这个有吗？

**Comment by imyhxy** [comment]
现在可以把ip段分出来来了，点击check.bat也可以扫ip，但是运行python check.py命令时出现了错误

~/workspace/checkiptools-master $ python checkip.py 
Traceback (most recent call last):
  File "checkip.py", line 1073, in <module>
    files = os.listdir(g_filedir)
OSError: [Errno 2] No such file or directory: ' '

我系统的python版本是

$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by xyuanmu** [comment]
@imyhxy 抱歉，更新代码基本上都是在Windows，没注意Linux，已修复：https://github.com/xyuanmu/checkiptools/commit/85dc233e808a466a403cee53ee5e5cff9c507664
更新下checkip.py即可。

**Comment by 825941933** [comment]
大神们，太牛了！佩服！

**Comment by imyhxy** [comment]
非常感谢

**Comment by lsnmx** [comment]
@xyuanmu begin check googleip-008.txt
[MainThread]load last result,ok cnt:46,ok file line:0,error cnt: 2538755
[Thread-1]begin to get ramdom ip
[MainThread]need create max threads count: 400
[Thread-1]load extra ip ok,line:7,load default ip: 0
[Thread-133]129 ip timeout
[Thread-129]129 ip timeout
[Thread-313]129 ip timeout
[Thread-97]129 ip timeout
[Thread-93]129 ip timeout
[Thread-101]129 ip timeout
[Thread-137]129 ip timeout
[Thread-204]129 ip timeout
[Thread-352]129 ip timeout
[Thread-25]129 ip timeout
[Thread-370]129 ip timeout
[Thread-268]129 ip timeout
啥问题啊大神，ip_tmperror.txt扫到38M现在所有IP超时了，重启机器还是如此

**Comment by xyuanmu** [comment]
@lsnmx 看源码，是记录失败的IP，每超过128个IP清理一次，你中途是不是退出过，每次扫描都要遍历一遍ip_tmperror.txt的。

**Comment by lsnmx** [comment]
就是中途退去过啊，不会又要我删除googleip-008.txt，重扫一次吧，不科学啊

**Comment by lsnmx** [comment]
@xyuanmu

**Comment by lsnmx** [comment]
@xyuanmu 大神是不是只能删除ip_tmperror.txt重扫了啊

**Comment by xyuanmu** [comment]
应该不用吧，error cnt: 2538755 错误的IP有2百多万，等遍历一遍ip_tmperror.txt就会开始扫的。

**Comment by lsnmx** [comment]
这个不知道是设计缺陷还是BUG啊，浪费时间，大神修改一下吧，哈哈checkgoogleip潜水了，没办法

**Comment by lsnmx** [comment]
@xyuanmu

**Comment by CNMan** [comment]
退出也不是从头来过，ip_tmperror、ip_tmpno都会自动略过扫剩下的

**Comment by xyuanmu** [comment]
@lsnmx 不是BUG，如果没有遍历ip_tmperror.txt，你重开就要重新扫描这2百万的IP了，相对来说比充扫要省很多时间，所以IP库大就尽量别中途退出。

**Comment by CNMan** [comment]
亚太的IP我用一个月时间在VPS上扫完了，正在VPS上重新扫整理出来的IP段
弄完在树莓派上只扫ip_tmpok就行了:)
![2015-11-03_135532](https://cloud.githubusercontent.com/assets/8692234/10901989/abb8d8d6-8232-11e5-8558-785685f5deec.png)

**Comment by xyuanmu** [comment]
@CNMan 看来存活的IP数量不少，树莓派用来扫描和FQ应该挺不错的:smile:。
看到IP总数突然想到合并tmp目录下OK文件中的IP，顺便更新了下[iptools](https://github.com/xyuanmu/checkiptools/commit/81e4a886768bc2f0e3f8823b027dd123e8e603ab)。

**Comment by CNMan** [comment]
@xyuanmu 已有的ok数量是220150，昨天本地过了一遍剩下6327，最近貌似复活不少，已经共享的IP段应该也能扫出来不少，其实共享的那些段是大头，ok大概有13万左右

**Comment by lsnmx** [comment]
@CNMan 你利害啊！

**Comment by lsnmx** [comment]
@xyuanmu 遍历ip_tmperror.txt了一晚上还是显示超时，看来真不能退去

**Comment by xyuanmu** [comment]
@lsnmx 现在日志还是全都是 129 ip timeout 吗？

**Comment by lsnmx** [comment]
@xyuanmu 
"连接超时设置"
g_conntimeout = 5
g_handshaketimeout = 7

**Comment by lsnmx** [comment]
@xyuanmu 删除ip_tmperror.txt重扫还是
[Thread-348]Catch IO Exception(42.146.202.60): [Errno 10061] , times:1357 ms
[Thread-79]129 ip timeout
[Thread-173]Catch IO Exception(42.147.238.150): [Errno 10061] , times:1724 ms
[Thread-45]129 ip timeout
[Thread-43]129 ip timeout
[Thread-38]129 ip timeout
[Thread-278]129 ip timeout
[Thread-37]129 ip timeout
[Thread-49]Catch IO Exception(42.146.215.250): [Errno 10061] , times:1428 ms
[Thread-70]129 ip timeout
[Thread-135]129 ip timeout
[Thread-81]129 ip timeout
[Thread-17]129 ip timeout
[Thread-108]129 ip timeout
[Thread-267]129 ip timeout
[Thread-154]129 ip timeout
[Thread-149]129 ip timeout
[Thread-163]129 ip timeout
[Thread-211]Catch IO Exception(42.147.3.86): [Errno 10061] , times:1316 ms
[Thread-396]129 ip timeout
[Thread-224]129 ip timeout
[Thread-223]129 ip timeout
[Thread-63]129 ip timeout
[Thread-318]129 ip timeout
[Thread-165]129 ip timeout
[Thread-167]129 ip timeout
[Thread-117]129 ip timeout
[Thread-242]129 ip timeout
[Thread-270]129 ip timeout
[Thread-142]129 ip timeout
[Thread-384]129 ip timeout
[Thread-347]129 ip timeout
[Thread-380]129 ip timeout
[Thread-280]129 ip timeout
[Thread-35]129 ip timeout
[Thread-138]129 ip timeout
[Thread-56]129 ip timeout
[Thread-4]129 ip timeout
[Thread-383]129 ip timeout
[Thread-194]129 ip timeout
[Thread-26]129 ip timeout
[Thread-203]129 ip timeout
[Thread-379]129 ip timeout
[Thread-290]129 ip timeout

**Comment by CNMan** [comment]
@lsnmx 除了内存，路由器性能也很重要，1000线程差的路由器会拥塞，导致你这种结果

**Comment by xyuanmu** [comment]
@lsnmx 排除硬件原因，应该是这段IP本身的问题了，也许是刚好某地区无法联通导致大面积timeout。

**Comment by Lrevor** [comment]
扫的太快太频繁，谷歌会禁你IP的

**Comment by lsnmx** [comment]
@xyuanmu 开400而已，ROS路由能顶住的，已经跑了6000W了

**Comment by lsnmx** [comment]
@xyuanmu 估计是段IP本身的问题了，删除了ip_tmperror.txt马上又正常了

**Comment by CNMan** [comment]
@Lrevor 官方的IP段会有这种，其他的不会
64.18.0.0/20 
64.233.160.0/19
66.102.0.0/20
66.249.80.0/20
72.14.192.0/18
74.125.0.0/16
173.194.0.0/16
207.126.144.0/20
209.85.128.0/17
216.58.192.0/19
216.239.32.0/19

**Comment by lsnmx** [comment]
@xyuanmu 8. 整合tmp目录下的可用IP到 ip_all.txt 得到ip_all.txt后能不能增加一个批处理 提取 ip_all.txt 中的IP, 并生成 ip_bind.txt, 用｜分隔，现在得手动修改ip_all.txt为ip_tmpok.txt才能提取出来IP，大神麻烦了

**Comment by lsnmx** [comment]
@xyuanmu 
5. 统计 googleip.txt 中的IP数量, 超过1KW自动分割报错
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files (x86)\Goagent X\CheckIptools\!iptools.py", line 399, in <module>
    main()
  File "D:\Program Files (x86)\Goagent X\CheckIptools\!iptools.py", line 386, in main
    test_load()
  File "D:\Program Files (x86)\Goagent X\CheckIptools\!iptools.py", line 240, in test_load
    ip_amount = test_ip_amount(ip_range_list)
  File "D:\Program Files (x86)\Goagent X\CheckIptools\!iptools.py", line 221, in test_ip_amount
    begin, end = ip_utils.split_ip(ip)
  File "D:\Program Files (x86)\Goagent X\CheckIptools\python27.zip\ip_utils.py", line 109, in split_ip
ValueError: too many values to unpack

**Comment by lsnmx** [comment]
@xyuanmu 补充一下直接执行5. 统计 googleip.txt 中的IP数量, 超过1KW自动分割报错，必需把IP段放到ip_range_origin.txt，执行4. 整合 ip_range_origin.txt  中的IP段, 并生成 googleip.txt再执行5. 统计 googleip.txt 中的IP数量, 超过1KW自动分割，不知道这是为何

**Comment by xyuanmu** [comment]
@lsnmx 检查一下googleip.txt是不是有一行有两个斜杠 /

**Comment by lsnmx** [comment]
@xyuanmu 好像自动分割有BUG,googleip.txt根本就没有.0.0.IP段，现在分割出来导致了出来很多.0.0.IP段，好可怕啊，比如googleip.txt只有50.128.128.0/7，分割分出了50.0.0.0/7，好可怕啊，单独分割50.128.128.0/7是正常的
[googleip.txt](https://github.com/phuslu/goproxy/files/40713/googleip.txt)

**Comment by xyuanmu** [comment]
可能你不懂CIDR，50.128.128.0/7表示有2的7次方相同的区间：50.0.0.0-51.255.255.255，用其中任何IP后面加上/7都表示相同的区间。
`如：50.128.128.0/7 = 50.0.0.0/7 = 51.0.0.0/7 = 50.1.2.3/7`

**Comment by CNMan** [comment]
@xyuanmu 
@lsnmx 他是不是要扫完全球IP啊，强大！

我扫完亚太的就没扫了，目前VPS上弄了定时任务，googleip每2小时扫一次，nogoogleip每8小时扫一次
再隔几天把其中证书是google.com和*.google.com的(近5.8万个)拿回来本地扫，大概能剩2000个可用

**Comment by lsnmx** [comment]
@xyuanmu 
@CNMan  小学文化没办法啊，大神晃要见笑了，整个IP段分割出来了400多个10000W哎啃不下了啊，又没天河一号，实在是啃不下了

**Comment by lsnmx** [comment]
@CNMan 很多以前的IP段都复活了啊，刚刚重新整理扫了一次以前的
