### ISSUE TITLE
求助！goagent报错

### ISSUE THREAD

**Issue by wangbingqian** [phuslu/goproxy#306]
win 10 企业版，之前没问题，后来就开始这样了：
ERROR - [Dec 12 10:44:00] ssl.wrap_socket(connection=<socket at 0x36d4d10 fileno=1288 sock=127.0.0.1:8087 peer=127.0.0.1:50402>) failed: (-1, 'Unexpected EOF')
Traceback (most recent call last):
  File "C:\goagent-3.0\local\proxylib.py", line 1003, in handle
  File "C:\goagent-3.0\local\proxylib.py", line 1069, in do_ssl_handshake
  File "C:\goagent-3.0\local\proxylib.py", line 438, in do_handshake
  File "C:\goagent-3.0\local\proxylib.py", line 420, in __iowait
SysCallError: (-1, 'Unexpected EOF')

ssl的问题？该怎么处理？

**Comment by jasonliul** [comment]
版本? 所用IP?

**Comment by wangbingqian** [comment]
3.2.3，IP是自己添加的，在Mac上用没问题，直接拷到win上的

**Comment by jasonliul** [comment]
CNMan 大大之前分享的字段, 有些好的被做成集成版, 因此负荷过重.

试试这些
49.231.60.196|49.231.60.212|49.231.60.206|49.231.60.199|49.231.60.207|49.231.60.209|49.231.60.239|49.231.60.198|49.231.60.210|49.231.60.220|49.231.60.242|49.231.60.251|49.231.60.225|49.231.60.248

**Comment by wangbingqian** [comment]
应该和IP没关系吧，我的Mac用着正常啊，另外一个win7也没事

**Comment by johnsonz** [comment]
ip问题，换一批就行了

**Comment by wangbingqian** [comment]
找到问题了，是KMS和极速版迅雷导致的，重装、卸载了N多遍终于找到问题根源了

**Comment by jasonliul** [comment]
@wangbingqian 
恭喜恭喜

**Comment by TaikooS** [comment]
@wangbingqian 具体如何解决? 只是卸载这两者?

**Comment by wangbingqian** [comment]
@TaikooS 这个你要看具体的情况，逐个去排查，我也是折腾了很久找到的。每个电脑情况可能不一样，自己去试试吧

**Comment by TaikooS** [comment]
@wangbingqian 好吧，我现在的问题是开着全局用IE访问g家网站毫无障碍，但用Chrome就会让goagent出现unexpected EOF的错误

**Comment by wangbingqian** [comment]
@TaikooS 那应该是chrome版本的问题了吧

**Comment by TaikooS** [comment]
@wangbingqian 卸载迅雷极速版后解决了……我怀疑是其多浏览器支持的问题，装回来再观察一下看看 - -

**Comment by wangbingqian** [comment]
@TaikooS 迅雷这个我也是Google时发现的，然后试了下，然后黄狗就活了，果断卸载极速版，装了个VIP尊享版倒是没事

**Comment by TaikooS** [comment]
@wangbingqian 唔，总之多谢你提供的线索

**Comment by wangbingqian** [comment]
@TaikooS 不客气，有问题多多交流，😁

**Comment by xubin990510** [comment]
If this successfully solved your problem, close the issue!

**Comment by argalisheep** [comment]
我去刚真是迅雷极速版的问题，我卸了以后果真好用了。
