### ISSUE TITLE
phuslu大神及各位大大帮忙看明原因出在那里

### ISSUE THREAD

**Issue by snowink** [phuslu/goproxy#33]
各位大神：请教一下各位，我的goproxy老是无法部署成功是什么原因呀，也不知那里出的错，大神帮看一下吧！另外还想问一下，当前自己所用的appids在goagent上可用，在goproxy上还需要重新重新上传吗，希望大神帮忙解决一下吧！感激ing.......
r112的还是不行，从开始测试到现在每个版本都会出现下边的信息
------------------------------------------------------
GoProxy Version    : r104 (go/go1.4.2 windows/amd64)
Listen Address     : 127.0.0.1:8000
RoundTrip Filters  : autoproxy,auth,php,gae,direct
Pac Server         : http://127.0.0.1:8000/proxy.pac
------------------------------------------------------
I0721 23:47:28.205466    7484 autoproxy.go:127] start updater for &autoproxy.GFW
List{URL:(*url.URL)(0xc0820100e0), Filename:"gfwlist.txt", Encoding:"base64", Du
ration:86400000000000}
I0721 23:47:28.234466    7484 main.go:178] ListenAndServe on 127.0.0.1:8000
I0721 23:47:35.437471    7484 php.go:103] 127.0.0.1:57530 "PHP GET http://www.yo
utube.com/ HTTP/1.1" 405
I0721 23:47:35.999465    7484 php.go:103] 127.0.0.1:57530 "PHP GET http://www.yo
utube.com/favicon.ico HTTP/1.1" 405
I0721 23:47:46.101466    7484 stripssl.go:126] 127.0.0.1:57532 "STRIP CONNECT 5-
edge-chat.facebook.com:443 HTTP/1.1" - -
I0721 23:47:46.102465    7484 stripssl.go:170] generate certificate for *.facebo
ok.com...
Exception 0xc000001d 0x0 0x0 0x661f4e
PC=0x661f4e

crypto/elliptic.p256MovCond(0xc0844eb320, 0xc, 0xc, 0xc0844eb320, 0xc, 0xc, 0xc0
844eb260, 0xc, 0xc, 0xb, ...)
        /go/src/crypto/elliptic/p256_asm_amd64.s:82 +0x1e
crypto/elliptic.p256ScalarMult(0xc0844eb260, 0xc0844eb260, 0xc0842c70f0, 0x4, 0x
4)
        /go/src/crypto/elliptic/p256_amd64.go:461 +0x10c9
crypto/elliptic.p256Curve.ScalarMult(0xc084460780, 0xc0844f2ea0, 0xc0844f2ec0, 0
xc084462040, 0x20, 0x20, 0xc0844f2ec0, 0x1a)
        /go/src/crypto/elliptic/p256_amd64.go:228 +0x376
crypto/tls.(*ecdheKeyAgreement).processClientKeyExchange(0xc08445d280, 0xc084430
480, 0xc08445ae10, 0xc0844ef0e0, 0x303, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/crypto/tls/key_agreement.go:298 +0x264
crypto/tls.(*serverHandshakeState).doFullHandshake(0xc0844378c0, 0x0, 0x0)
        /go/src/crypto/tls/handshake_server.go:467 +0x135e
crypto/tls.(*Conn).serverHandshake(0xc0820b3080, 0x0, 0x0)
        /go/src/crypto/tls/handshake_server.go:70 +0x336
crypto/tls.(*Conn).Handshake(0xc0820b3080, 0x0, 0x0)
        /go/src/crypto/tls/conn.go:979 +0x16e
github.com/phuslu/goproxy/httpproxy/filters/stripssl.(*Filter).Request(0xc0820ea
000, 0xc082004370, 0xc0820c8340, 0xc082004370, 0xc0820c8340, 0x0, 0x0)
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/filters/stri
pssl/stripssl.go:136 +0x83f
github.com/phuslu/goproxy/httpproxy.Handler.ServeHTTP(0x0, 0x0, 0x291a00, 0xc082
0dc240, 0xc0820e41c0, 0x2, 0x2, 0xc082084000, 0x5, 0x8, ...)
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/handler.go:4
9 +0x1e7
github.com/phuslu/goproxy/httpproxy.(*Handler).ServeHTTP(0xc082010620, 0x291c30,
 0xc082088960, 0xc0820c8340)
        <autogenerated>:7 +0xda
net/http.serverHandler.ServeHTTP(0xc082044420, 0x291c30, 0xc082088960, 0xc0820c8
340)
        /go/src/net/http/server.go:1703 +0x1a1
net/http.(*conn).serve(0xc0820888c0)
        /go/src/net/http/server.go:1204 +0xb5e
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:1751 +0x365

goroutine 1 [chan receive]:
main.main()
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/goproxy/main.go:185 +0
x1a81

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xb596c0)
        /home/phuslu/GOPATH/src/github.com/golang/glog/glog.go:879 +0x7f
created by github.com/golang/glog.init路1
        /home/phuslu/GOPATH/src/github.com/golang/glog/glog.go:410 +0x2ae

goroutine 7 [syscall]:
os/signal.loop()
        /go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init路1
        /go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 8 [sleep]:
github.com/phuslu/goproxy/httpproxy/filters/autoproxy.(*Filter).updater(0xc0820e
a180)
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/filters/auto
proxy/autoproxy.go:130 +0x123
github.com/phuslu/goproxy/httpproxy/filters/autoproxy.*Filter.(github.com/phuslu
/goproxy/httpproxy/filters/autoproxy.updater)路fm()
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/filters/auto
proxy/autoproxy.go:117 +0x2e
sync.(*Once).Do(0xb66c30, 0xc0820e8340)
        /go/src/sync/once.go:44 +0xdb
created by github.com/phuslu/goproxy/httpproxy/filters/autoproxy.NewFilter
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/filters/auto
proxy/autoproxy.go:117 +0x851

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc082666170, 0x72, 0x0, 0x0)
        /go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082042060, 0xc082666060, 0x9004d0, 0x8, 0xc0820e8d80, 0xc
0820f0300, 0x0, 0x0)
        /go/src/net/fd_windows.go:188 +0x305
net.(*netFD).acceptOne(0xc082666000, 0xc0820bc0e0, 0x2, 0x2, 0xc082666060, 0x0,
0x0, 0x0)
        /go/src/net/fd_windows.go:558 +0x547
net.(*netFD).accept(0xc082666000, 0x0, 0x0, 0x0)
        /go/src/net/fd_windows.go:585 +0x17a
net.(*TCPListener).AcceptTCP(0xc082042090, 0x794720, 0x0, 0x0)
        /go/src/net/tcpsock_posix.go:234 +0x55
net.(*TCPListener).Accept(0xc082042090, 0x0, 0x0, 0x0, 0x0)
        /go/src/net/tcpsock_posix.go:244 +0x53
github.com/phuslu/goproxy/httpproxy.(*listener).startListen(0xc0820dc240)
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/listener.go:
167 +0x5f
created by github.com/phuslu/goproxy/httpproxy.ListenTCP
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/listener.go:
128 +0xab8

goroutine 10 [chan receive]:
github.com/phuslu/goproxy/httpproxy.(*listener).Accept(0xc0820dc240, 0x0, 0x0, 0
x0, 0x0)
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/httpproxy/listener.go:
189 +0x85
net/http.(*Server).Serve(0xc082044420, 0x291a78, 0xc0820dc240, 0x0, 0x0)
        /go/src/net/http/server.go:1728 +0x99
created by main.main
        /home/phuslu/GOPATH/src/github.com/phuslu/goproxy/goproxy/main.go:179 +0
x183b

goroutine 17 [IO wait]:
net.(*pollDesc).Wait(0xc0820f0170, 0x72, 0x0, 0x0)
        /go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082042060, 0xc0820f0060, 0x8eff40, 0x7, 0x9cf1f0, 0xb1515
c, 0x0, 0x0)
        /go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820f0000, 0xc08200f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc0820ca010, 0xc08200f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/net.go:121 +0xe3
net/http.(*liveSwitchReader).Read(0xc082088048, 0xc08200f000, 0x1000, 0x1000, 0x
417669, 0x0, 0x0)
        /go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc0820da0a0, 0xc08200f000, 0x1000, 0x1000, 0xc08210e38
0, 0x0, 0x0)
        /go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc082612000)
        /go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc082612000, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc082612000, 0x0, 0x0, 0x0, 0xc081f9df00, 0x0, 0x0)
        /go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc082620780, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc082620780, 0x0, 0x0, 0x0, 0x0)
        /go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc082612000, 0xc0820c8270, 0x0, 0x0)
        /go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc082088000, 0x0, 0x0, 0x0)
        /go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc082088000)
        /go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:1751 +0x365

goroutine 33 [IO wait]:
net.(*pollDesc).Wait(0xc0820b62f0, 0x72, 0x0, 0x0)
        /go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082042060, 0xc0820b61e0, 0x8eff40, 0x7, 0x9cf1f0, 0x0, 0x
0, 0x0)
        /go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820b6180, 0xc08250f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082042048, 0xc08250f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/net.go:121 +0xe3
net/http.noteEOFReader.Read(0x291b38, 0xc082042048, 0xc08209a268, 0xc08250f000,
0x1000, 0x1000, 0x80fe20, 0x0, 0x0)
        /go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc0820da340, 0xc08250f000, 0x1000, 0x1000, 0xc08
2014d00, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc0820447e0)
        /go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc0820447e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc08209a210)
        /go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        /go/src/net/http/transport.go:660 +0xca6

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc08209a210)
        /go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        /go/src/net/http/transport.go:661 +0xcc3
rax     0xc0844eb320
rbx     0xb
rcx     0xc0844eb260
rdx     0xc
rdi     0xc0844eb320
rsi     0xc0844eb320
rbp     0xc0844eb260
rsp     0xc0842c6fd0
r8      0x0
r9      0x0
r10     0xffffffffffffffff
r11     0xffffffff
r12     0x0
r13     0xffffffff00000001
r14     0xb
r15     0x0
rip     0x661f4e
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by fletchere** [comment]
你是想用php还是用gae?

**Comment by snowink** [comment]
想先测试下GAE

**Comment by fletchere** [comment]
那就在main.json 中把gae放在php前面。
