### ISSUE TITLE
r201 run error on linux

### ISSUE THREAD

**Issue by yuan78** [phuslu/goproxy#383]
r201 run error on linux (hv uncomented auth in main.json, but still report no auth.json error):

# ./goproxy

ERROR: logging before flag.Parse: F0308 13:35:24.476366   10845 auth.go:43] storage.ReadJsonConfig("auth.json") failed: stat auth.json: no such file or directory
goroutine 1 [running, locked to thread]:
github.com/golang/glog.stacks(0xc84a00, 0x0, 0x0, 0x0)
	/home/phuslu/gopath/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xc67dc0, 0xc800000003, 0xc8200ce0c0, 0xc45059, 0x7, 0x2b, 0x0)
	/home/phuslu/gopath/src/github.com/golang/glog/glog.go:720 +0x2ce
github.com/golang/glog.(*loggingT).printf(0xc67dc0, 0xc800000003, 0xa619e0, 0x26, 0xc82004bf18, 0x2, 0x2)
	/home/phuslu/gopath/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0xa619e0, 0x26, 0xc82004bf18, 0x2, 0x2)
	/home/phuslu/gopath/src/github.com/golang/glog/glog.go:1148 +0x5d
_/home/phuslu/goproxy/httpproxy/filters/auth.init.1()
	/home/phuslu/goproxy/httpproxy/filters/auth/auth.go:43 +0x24d
_/home/phuslu/goproxy/httpproxy/filters/auth.init()
	/home/phuslu/goproxy/httpproxy/filters/auth/auth.go:136 +0x68
main.init()
	/home/phuslu/goproxy/main.go:237 +0x99

**Comment by jzp820927** [comment]
failed: stat auth.json: no such file or directory

提示说，没找到 auth.json 这个文件，是不是你把这个文件删了？

**Comment by hcym** [comment]
我的没问题

就是不能用新的服务端

**Comment by wzdnzd** [comment]
[https://github.com/phuslu/goproxy/issues/380](url)和我的一样，先进入goproxy目录下就不会报错，见#380

**Comment by yuan78** [comment]
@wzdnzd , yes, you are correct, you can only run goproxy when you must cd goproxy directory first . 
And it's no use when run it by absolute path or desktop shortcut, it's a crazy bug for goproxy, hope  phuslu can fix it soon.
