### ISSUE TITLE
请问mac如何使用，找不到gogagent-osx.command 只有一个12M的goproxy

### ISSUE THREAD

**Issue by KwToPA** [phuslu/goproxy#443]
运行这个报错 
Last login: Wed Mar 30 10:12:08 on ttys001
/Users/A/Documents/goproxy/goproxy ; exit;
nnnnnn:~ A$ /Users/A/Documents/goproxy/goproxy ; exit;
-bash: /Users/A/Documents/goproxy/goproxy: cannot execute binary file
logout

[Process completed]

**Comment by jzp820927** [comment]
goproxy_darwin_386-r306.tar.bz2
goproxy_darwin_amd64-r306.tar.bz2

mac 用这个

**Comment by KwToPA** [comment]
@jzp820927 谢谢，还有几个问题想请教
1、main.json里有一条代码是`"Addr": "127.0.0.1:8087",` 所以SwitchyOmega里要设置成127.0.0.1:8087 ？
2、gae.json 里的`	"Scheme": "https",`是不是意味着强制走https？
3、为了防止流量被盗，	`	"Password": "",`加密后如何重新上传？
4、以前的goagent里可以设置dnsproxy，请问现在的goproxy里面能设置吗？
5、请问如何突破youtube的地区限制？

**Comment by KwToPA** [comment]
双击后报错：
~/goproxy_darwin_amd64-r305/goagent-osx.command ; exit;
logout

[Process completed]

cd之后 sudo ~/goproxy_darwin_amd64-r305/goagent-osx.command
goproxy_darwin_amd64-r305 ’用户名‘$ Traceback (most recent call last):
  File "/Users/’用户名‘/Downloads/goproxy_darwin_amd64-r305/goagent-osx.command", line 46, in <module>
    from PyObjCTools import AppHelper
ImportError: No module named PyObjCTools

**Comment by phuslu** [comment]
@KwToPA 你的 mac osx 的版本似乎太老了， 没有完整的 pyobjc 的支持.

**Comment by jzp820927** [comment]
@KwToPA 1、就是这样设置
2、应该是强制走 https 的意思
3、可以用 goagent 上传服务端，上传前修改服务端文件，把密码添加进去就可以了
4、目前goproxy 还没有 DNS 代理的功能
5、地区限制是个比较复杂的问题，要改 hosts 规则，具体看看 wiki 里面的介绍

**Comment by KwToPA** [comment]
@phuslu  作者你好，感谢你的回复
我的OS：10.10.5     pyobjc装不上
使用easy_install -U pyobjc，看到有一条`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`是因为我没装Xcode吗

以下是报错
`$ easy_install -U pyobjc
Searching for pyobjc
Reading https://pypi.python.org/simple/pyobjc/
Best match: pyobjc 3.1.1
Processing pyobjc-3.1.1-py2.7.egg
pyobjc 3.1.1 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyobjc-3.1.1-py2.7.egg
Processing dependencies for pyobjc
Searching for pyobjc_framework-SceneKit==3.1.1
Reading https://pypi.python.org/simple/pyobjc_framework-SceneKit/
Best match: pyobjc-framework-SceneKit 3.1.1
Downloading https://pypi.python.org/packages/source/p/pyobjc-framework-SceneKit/pyobjc-framework-SceneKit-3.1.1.tar.gz#md5=679ea9ff702068ba1e0cb78645e8dea7
Processing pyobjc-framework-SceneKit-3.1.1.tar.gz
Writing /var/folders/ff/lbzkbp_x7795pp0rpfzqh6lw0000gn/T/easy_install-pw9QvO/pyobjc-framework-SceneKit-3.1.1/setup.cfg
Running pyobjc-framework-SceneKit-3.1.1/setup.py -q bdist_egg --dist-dir /var/folders/ff/lbzkbp_x7795pp0rpfzqh6lw0000gn/T/easy_install-pw9QvO/pyobjc-framework-SceneKit-3.1.1/egg-dist-tmp-7WSbDA
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==20.4', 'console_scripts', 'easy_install')()
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 2241, in main
    
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 391, in run
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 675, in install_item
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 717, in process_distribution
    
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 850, in install_eggs
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 1078, in build_and_install
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 1064, in run_setup
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 246, in run_setup
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 166, in save_modules
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 141, in resume
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 154, in save_modules
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 243, in run_setup
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 273, in run
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 242, in runner
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/var/folders/ff/lbzkbp_x7795pp0rpfzqh6lw0000gn/T/easy_install-pw9QvO/pyobjc-framework-SceneKit-3.1.1/setup.py", line 42, in <module>
  File "/var/folders/ff/lbzkbp_x7795pp0rpfzqh6lw0000gn/T/easy_install-pw9QvO/pyobjc-framework-SceneKit-3.1.1/pyobjc_setup.py", line 496, in setup
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/dist.py", line 269, in __init__
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 827, in resolve
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 1072, in best_match
  File "build/bdist.macosx-10.6-x86_64/egg/pkg_resources/__init__.py", line 1084, in obtain
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 640, in easy_install
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 670, in install_item
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 850, in install_eggs
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 1078, in build_and_install
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/command/easy_install.py", line 1064, in run_setup
    
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 246, in run_setup
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 166, in save_modules
  File "build/bdist.macosx-10.6-x86_64/egg/setuptools/sandbox.py", line 140, in resume
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes at least 3 arguments (1 given)
`

@jzp820927   你好 感谢回复
5、我记得以前goagent突破地区限制很简单，不知goproxy有这种功能吗？
以前是这样的 改proxy.ini
`[profile]
...
https?://www\.youtube\.com/watch = google_hk
.c.youtube.com =
.youtube.com = google_hk
.googlevideo.com =
upload.facebook.com:443 = `
取消注释就行了

**Comment by jzp820927** [comment]
@KwToPA  规则应该是在 gae.json 文件的 "Site2Alias" 段，你按照他的格式，把以前 goagent 的规则添加进去，看行不行吧，gop 还在开发中，不知道能不能生效

**Comment by KwToPA** [comment]
@jzp820927  好的 谢谢
