### ISSUE TITLE
一直用GoAgent和xx-net，我到现在还没有设置好go

### ISSUE THREAD

**Issue by KeymanLai** [phuslu/goproxy#459]
界面显示如下：
ERROR: logging before flag.Parse: F0401 21:03:47.392871    3896 gae.go:66] stora
ge.ReadJsonConfig("gae.json") failed: invalid character ']' looking for beginnin
g of value
goroutine 1 [running, locked to thread]:
github.com/golang/glog.stacks(0xaaf100, 0x0, 0x0, 0x0)
        /home/rof/src/github.com/golang/glog/glog.go:769 +0xac
github.com/golang/glog.(*loggingT).output(0xa9dbe0, 0x3, 0x1122ac80, 0xa818fc, 0
x6, 0x42, 0x0)
        /home/rof/src/github.com/golang/glog/glog.go:720 +0x267
github.com/golang/glog.(*loggingT).printf(0xa9dbe0, 0x3, 0x8e7980, 0x26, 0x110eb
f7c, 0x2, 0x2)
        /home/rof/src/github.com/golang/glog/glog.go:655 +0x161
github.com/golang/glog.Fatalf(0x8e7980, 0x26, 0x110ebf7c, 0x2, 0x2)
        /home/rof/src/github.com/golang/glog/glog.go:1148 +0x52
_/home/rof/goproxy/httpproxy/filters/gae.init.1()
        /home/rof/goproxy/httpproxy/filters/gae/gae.go:66 +0x1b7
_/home/rof/goproxy/httpproxy/filters/gae.init()
        /home/rof/goproxy/httpproxy/filters/gae/gae.go:173 +0x7f
main.init()
        /home/rof/goproxy/main.go:237 +0xb0
帮我看看哪里设置错误

**Comment by jzp820927** [comment]
应该是你的 gae.json 配置文件有问题，检查下

**Comment by KeymanLai** [comment]
{
	"AppIDs": [
		"k*****1",
		"k************1",
		"k***********3",
		"k*********1",
		"k************",
		"l************",
		"l************",
		"l***********",
		"l***********",
		"l****************"
	],
	"Scheme": "https",
	"Domain": "appspot.com",
	"Path": "/_gh/",
	"Password": "",
	"SSLVerify": false,
	"Sites": [
		"*"
	],
	"HostMap" : {
		"google_hk": [
			"222.251.134.119",
			"110.164.8.50",
			"110.164.8.20",
			"222.251.134.93",
			"222.251.134.88",
			"110.164.8.30",
			"110.164.8.35",
			"202.86.162.172",
			"222.251.134.113",
			"222.251.134.99",
			"110.164.8.54",
			"110.164.8.29",
			"222.251.134.103",
			"110.164.8.49",
			"222.251.134.108",
			"202.86.162.172",
		],
		"google_talk": [
			"talk.google.com",
			"talk.l.google.com",
			"talkx.l.google.com"
		],


除了appid  用**表示外，我其它该项都是按照#243改的。怎么还是报错，麻烦各位帮我看看哪里出错了
麻烦你帮我检查下吧!   感谢了

**Comment by KeymanLai** [comment]
[https://github.com/phuslu/goproxy/issues/243](url)

**Comment by KeymanLai** [comment]
我都是按照这个操作的。https://github.com/phuslu/goproxy/issues/243

**Comment by angle1895** [comment]
"222.251.134.108",
"202.86.162.172"
],

**Comment by angle1895** [comment]
最后一行无 ,

**Comment by KeymanLai** [comment]
哦，原来如此，可以了，设置好了。谢谢两位哈。
