### ISSUE TITLE
go_gae_server 服务端应怎么使用，部署了，但用不了

### ISSUE THREAD

**Issue by gxggsrmyy** [phuslu/goproxy#489]
http.HandleFunc("/_gh/", handler)
	http.HandleFunc("/favicon.ico", favicon)
	http.HandleFunc("/robots.txt", robots)
	http.HandleFunc("/", root)

访问/_gh/ 会500错误

**Comment by gxggsrmyy** [comment]
访问 / 返回 GoProxy server 1.0 works, deployed at 2016-04-06T21:26:02Z

**Comment by phuslu** [comment]
奇怪啊，我访问时好好的啊。

**Comment by gxggsrmyy** [comment]
部署的app.yaml 文件如下所示，对吗？

application: g169
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

**Comment by gxggsrmyy** [comment]
application: g169
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

**Comment by gxggsrmyy** [comment]
application: g169
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*

  script: _go_app

**Comment by phuslu** [comment]
你照这个部署一次呢 https://github.com/phuslu/goproxy/blob/wiki/SimpleGuide.md

**Comment by gxggsrmyy** [comment]
handlers: 只有路由 / 
url: /.*
没有路由 /_gh/吗

**Comment by gxggsrmyy** [comment]
我用同样的方法部署的goagent 服务端都没有问题

**Comment by hotbbs** [comment]
go_gae_server 服务端和以前的服务端相比，有啥优势？

**Comment by jzp820927** [comment]
@hotbbs 就好比 goproxy 相比 goagent 的优势

**Comment by hotbbs** [comment]
@jzp820927 能提升很多性能吧，哈哈，这样的话，我一会儿就更新了

**Comment by jzp820927** [comment]
反正我用 goproxy 比 goagent 快多了，go 语言的性能比 python 好，所以处理速度快。

**Comment by gxggsrmyy** [comment]
https://github.com/phuslu/goproxy/blob/wiki/SimpleGuide.md 按这个部署出错，我是直接用appcfg.py部署成功，直接用appcfg.py部署成功的goagent 服务端都没有问题

**Comment by phuslu** [comment]
虽然理论如此，但是实际上服务端性能提升不会很明显， 估计实测 5% 左右吧。

**Comment by phuslu** [comment]
@gxggsrmyy 奇怪，我再看看。

**Comment by jzp820927** [comment]
我也部署个 go 服务端试试，看有没有问题

**Comment by gxggsrmyy** [comment]
goproxy 能编译一个在openwrt 路由器上运行吗，可以就好了

**Comment by jzp820927** [comment]
goproxy_linux_arm-r359.tar.xz
Releases 里面不是有 arm 版本吗，一般路由器应该都是 arm 吧

**Comment by phuslu** [comment]
@gxggsrmyy @jzp820927 openwrt 一般是 MIPS 架构，go 官方还不支持。

如果要折腾的话，这里有个加上了 gccgo 的 openwrt https://github.com/GeertJohan/openwrt-go

**Comment by jzp820927** [comment]
@phuslu 树莓派应该可以用 arm 版吧?

**Comment by phuslu** [comment]
@jzp820927 是的。

**Comment by gxggsrmyy** [comment]
@phuslu 你试试直接用appcfg.py 部署一个goproxy服务端看看有没有问题

**Comment by hcym** [comment]
晕倒

是不能改版本号，密码也没加

终于用上GO服务端

**Comment by jzp820927** [comment]
刚刚部署了一个，没发现啥问题，访问 / 同样输出 GoProxy server 1.0 works 信息，但是 访问/_gh/ 页面上空白的，但是没有 500 错误

**Comment by gxggsrmyy** [comment]
@hcym 怎么弄

**Comment by gxggsrmyy** [comment]
@jzp820927 你是怎么样部署的

**Comment by jzp820927** [comment]
我在 linux 下面部署的，就是 git 源码，然后 python uploader.py ，然后输入 邮箱，密码，就自动开始部署了，然后提示 Deployment successful. 就 OK 了

**Comment by hcym** [comment]
因为一个id里有几个服务端

习惯部署时改版本号，加了密码，死活不行

刚刚看phuslu 说可以

干脆啥都不改直接上传，就OK了

似乎性能是有不少提高

**Comment by phuslu** [comment]
@hcym 我倾向认为性能提高只是理论存在的，实测我保守认为大多数时候感觉不出来。

**Comment by jzp820927** [comment]
@phuslu 你不是说，这服务端是一年前的代码嘛？和现在的 go 不合拍了，等你优化了，不就能感觉到了吗

**Comment by hcym** [comment]
E0406 23:38:40.485096    4931 handler.go:115] IoCopy &http.bodyEOFSignal{body:(*http.body)(0xc8294a8980), mu:sync.Mutex{state:0, sema:0x0}, closed:false, rerr:error(nil), fn:(func(error) error)(0x4d0650), earlyCloseFn:(func() error)(0x4d05f0)} return 4096 write tcp 127.0.0.1:8087->127.0.0.1:41172: write: broken pipe

@phuslu 经常出现broken pipe

而且代理上传也不行，还是老的GoAgent上传

性能应该是有提高，感觉明显

再次感谢老大回归，辛苦了

**Comment by phuslu** [comment]
write tcp 127.0.0.1:8087->127.0.0.1:41172: write: broken pipe

这种本地到本地 broken pipe 一般不是问题，应该是短时间打开很含有很多资源的网页并且迅速关闭导致的。

**Comment by hcym** [comment]
ok那就不管了

因为不懂码，又关了日志

喜欢保留空窗

**Comment by phuslu** [comment]
嗯，前段时间家中多了一个新成员（一位可爱的小天使），忙的不行。

现在也很少熬夜了，晚安。

**Comment by caofengzi** [comment]
@phuslu 
部署完成的app.yaml 文件如下所示，对吗社長？

application: g169
version: 1
runtime: go
api_version: go1

handlers:

url: /.* script: _go_app

**Comment by inkdie** [comment]
新的服务端，跟旧的客户端，兼容吗？

**Comment by jasonliul** [comment]
File "python27.py", line 95, in <module>
  File "D:\Temp\goproxy-server.gae\uploader.py", line 95, in <module>
    main()
  File "D:\Temp\goproxy-server.gae\uploader.py", line 82, in main
    upload('gae', appid)
  File "D:\Temp\goproxy-server.gae\uploader.py", line 68, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 3873, in main
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 2443, in Run
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 3638, in __call__
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 3141, in Rollback
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 3158, in _Rollback
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 2018, in Rollback
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppcfg.py", line 1698, in Send
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppengine_rpc.py", line 378, in Send
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppengine_rpc.py", line 436, in _Authenticate
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppengine_rpc.py", line 280, in _Authenticate
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppengine_rpc.py", line 232, in _GetAuthToken
  File "D:\Temp\goproxy-server.gae\google_appengine.zip\google\appengine\tools\a
ppengine_rpc.py", line 94, in __init__
AttributeError: can't set attribute

居然出错

**Comment by mouseroser** [comment]
邮箱密码有没有搞错，如果用的是gmail的话，需要重新设置应用专用密码的。

**Comment by MeABc** [comment]
已解决密码出错问题。重下或者单独下载单个gae.go文件。

**Comment by playnetcn** [comment]
@phuslu 打开goproxy-gui.exe之后，运行uploader.dat或者是通过vpn上传服务端总是报错，不知道啥原因，邮箱密码我输入是正确的，日志提示如下：
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\uploader.py", line
95, in <module>
    main()
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\uploader.py", line
82, in main
    upload('gae', appid)
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\uploader.py", line
68, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 3873, in main
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 2443, in Run
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 3638, in __call__
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 3141, in Rollback
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 3158, in _Rollback
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 2018, in Rollback
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appcfg.py", line 1698, in Send
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appengine_rpc.py", line 378, in Send
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appengine_rpc.py", line 436, in _Authenticate
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appengine_rpc.py", line 280, in _Authenticate
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appengine_rpc.py", line 232, in _GetAuthToken
  File "D:\软件\DL\goagent\goagent323\new\goproxy-server.gae\google_appengine.zi
p\google\appengine\tools\appengine_rpc.py", line 94, in __init__
AttributeError: can't set attribute
请按任意键继续. . .

（补充一下，上传能不能用ss的代理，ss比vpn快？）

**Comment by jzp820927** [comment]
@playnetcn uploader.py 文件里面可以设置代理，修改这个文件的下面这2行，有2处，试试应该可以

socket.create_connection(('127.0.0.1', 8087), timeout=1).close()
    os.environ['HTTPS_PROXY'] = '127.0.0.1:8087'

**Comment by jasonliul** [comment]
@hcym 
老的上传分享一个, 新的这个用vpn也不行.

找到另一个老版, 需要浏览器先登录appwngine, 但是上传...还是不行

**Comment by jzp820927** [comment]
@jasonliul 还用得着上传分享嘛，github 本来就是管理版本的，想下第一版都是 轻而易举的事情

**Comment by hcym** [comment]
@jasonliul 

这可说不准，有时干扰大也会失败

还有gae的安全保护要关

其他真没啥注意的

俺是早早就上传过，就是不能用

昨天才真正用上，今天一口气又上传几个都ok

**Comment by jasonliul** [comment]
@hcym 
查看黄历, 今日不宜上传

**Comment by playnetcn** [comment]
@jasonliul @jzp820927  @phuslu 
我知道上传失败的原因了，我总结一下。
一、首先要停用google邮箱两步验证。
二、修改gae.go文件增加密码
	Password = "写上密码"
三、修改uploader.py里面配置（端口号和ss代理一致）
     socket.create_connection(('127.0.0.1', 端口号), timeout=1).close()
     os.environ['HTTPS_PROXY'] = '127.0.0.1:端口号'
四、开启ss，执行uploader.bat上传
我刚才按这个方法上传了20个appid，全部成功。

**Comment by hcym** [comment]
@playnetcn 

和ss比较如何

heroku，openshift都不太够劲

我有个老heroku服务端APPP，用goproxy前置，速度很快
要是能前置代理一下就棒了

**Comment by playnetcn** [comment]
@hcym  ss效果好。

**Comment by jasonliul** [comment]
@phuslu 

社长, 俺要打你的pat.

简易教程里面差了一项提示.
到这里
https://www.google.com/settings/security/lesssecureapps
选择Turn On.

不然一旦上传, 会被谷歌拦截.
而且谷歌会Email提示

Someone just tried to sign in to your Google Account XXX from an app that doesn't meet modern security standards.

We strongly recommend that you use a secure app, like Gmail, to access your account. All apps made by Google meet these security standards. Using a less secure app, on the other hand, could leave your account vulnerable.

**Google stopped this sign-in attempt,** but you should review your recently used devices:

**Comment by jap33** [comment]
@playnetcn
照你的方法25个上传成功。

**Comment by cnrip** [comment]
@phuslu 上传不成功是代理自动中断连接,只要在上传时,随便打开一个需要代理的页面,隔十秒八秒就刷新一次页面,让代理保持着数据进出,就能成功上传部署.还有部署不同版本的问题,用UE修改app.yaml里version: 1为其它数字,在输入ID回车需要输入帐号和密码时,app.yaml文件里被修改的数字自动恢复为1,UE会提示文件已经被修改,是否重新载入,这是重新载入文件,把1修改为其它数字后保存,再输入帐号和密码,就能成功上传部署该数字的版本,但每次只能部署一个ID,下一个ID又会重新恢复为1.

**Comment by jap33** [comment]
从什么地方看服务端APP是goa还是gop呢？

**Comment by jasonliul** [comment]
@jap33 
http://yourID.appspot.com/
GoProxy server 1.0 works, deployed at

**Comment by jap33** [comment]
@jasonliul 
有无代理都打不开。出现
Error: Not Found
The requested URL / was not found on this server.

**Comment by jzp820927** [comment]
@jap33 那说明，你没部署成功

**Comment by playnetcn** [comment]
@jasonliul 知道怎么查询上传的版本信息了。@jap33 我查询了一下我的都部署成功，版本也是对的。
 大家有没有遇到上一会网页面就提示：
This page cannot be loaded using Chrome Data Saver. Try reloading the page.

**Comment by jzp820927** [comment]
这是 gzip 的IP，你的IP不稳定

**Comment by caofengzi** [comment]
@jzp820927 上傳提示部署成功了，可是訪問jasonliul 提供那個網址怎麼是空白頁呢？如果是空白頁是否部署成功，另外重新命名的gae.user.json文件是否也放在goproxy文件夾？是否用gae.user.json替換源程序的gae.json？還是共存？俺試過如果不共存程序不能啟動。

**Comment by jap33** [comment]
从这里看25个是成功的
https://console.cloud.google.com/appengine/versions?project=japanooo9924&moduleId=default&versionId=1

**Comment by cnrip** [comment]
@phuslu 确实很容易出现/_gh/错误,得重新载入GOPROXY才能打开页面,而且状况很频繁,服务端和客户端都全新部署了一次,问题依旧.同样的IP,用GOAGENT服务端就不会有这情况,再有就是某些站点的Cookie不能保持,登入后跳转还是登录页面.已经清空Cookie测试过很多次,换回GOAGENT服务端又一切正常.

**Comment by caofengzi** [comment]
@jasonliul訪問你提供的這個地址如果是空白頁而不是這個提示 Error: Not Found
The requested URL / was not found on this server.，是否代表服務端研究部署成功了。
http://yourID.appspot.com/

**Comment by jap33** [comment]
@caofengzi 
你gae.user.json文件有错误注意哪些小点点.。

**Comment by phuslu** [comment]
目前还有 bug ， 除非尝鲜，否则请勿使用。

**Comment by jzp820927** [comment]
还好我有 先见之明，只部署了一个 APPID 测试用，你们也太冲动了，25个，全部搞上了。

**Comment by cnrip** [comment]
我是上传了1和2两个版本,GA和GO各一个,现在服务端全改回用GAE服务端,但最新版客户端我发现也杯具了,也开始出现GH或404错误.

**Comment by inkdie** [comment]
如果上传两个版本的话，客户端怎么分辨该用哪个呢？

**Comment by phuslu** [comment]
问题已定位， 是客户端的问题，r372 应该已经修复。 请更新。

另外，go 语言服务端最好也更新一下， 有改进。

**Comment by jasonliul** [comment]
终于可以放心更新两端了

**Comment by jzp820927** [comment]
坐等测试结果

**Comment by jap33** [comment]
r372gae.json多了一段；
	"ForceGAE": [
		"translate.googleapis.com",

**Comment by jap33** [comment]
这就是伪军
			"www.l.google.com",
			"www2.l.google.com",
			"www3.l.google.com",
			"www4.l.google.com",
			"www.google.com"

**Comment by hcym** [comment]
有提高
