### ISSUE TITLE
goagent 404 要怎么改啊？？

### ISSUE THREAD

**Issue by jkng** [phuslu/goproxy#624]
ciphers='AES128-SHA'   默认这样 不行了

**Comment by phuslu** [comment]
ciphers='AES128-SHA256' 试下这个。

**Comment by jkng** [comment]
@phuslu  谢谢社长那么晚还回复，这个刚试了下还是不行

**Comment by jkng** [comment]
![qq 20160429015909](https://cloud.githubusercontent.com/assets/12867321/14896008/3aded2fc-0dae-11e6-8291-0d836a62b31d.png)

**Comment by jkng** [comment]
IP是刚换的。

**Comment by caofengzi** [comment]
@jkng 還是ip問題，俺沒有這個問題。配置是社長的默認配置。

**Comment by thundery1** [comment]
昨儿竟然不能看油管视频，今天正常了，吓死我了。。

**Comment by jzp820927** [comment]
我去，整版整版的黄字，大夸张了

**Comment by ytbcn** [comment]
@phuslu 社长帮忙弄一下goagent使用gvs的问题，这个ciphers='AES128-SHA256'不行，提示Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GoAgent-3.23\local\proxylib.py", line 204
1, in create_http_request
  File "C:\Users\Administrator\Desktop\GoAgent-3.23\local\proxylib.py", line 202
0, in create_ssl_connection
timeout: timed out

**Comment by jzp820927** [comment]
goa 社长早就不维护了

**Comment by jasonliul** [comment]
请大家追随社长, 使用新狗.

旧狗已经没有秘密, 旧狗所使用的ip, 也会被破墙自动统计收集, 
这样坚壁清野, 逐步搞残ip池, 现在可用ip成为珍惜濒危资源.

新狗在很多方面加强了安全性, 抗干扰能力.

**Comment by jzp820927** [comment]
不但要使用新狗，而且要使用 r422 以上版本的心狗。具体原因，社长有说明，详见：https://github.com/phuslu/goproxy/issues/600
