### ISSUE TITLE
gvs不能用于goagent了吗？大神帮忙解答下

### ISSUE THREAD

**Issue by anesliu** [phuslu/goproxy#645]
以前goagent3.2.3用gvs一直好好的，最近几天忽然不能用，大神解答下

**Comment by phuslu** [comment]
嗯。
goagent 不再维护了。主观和客观的原因都有。

可以考虑转到 goproxy， 相比 goagent 稳定快速。

除了配置文件变成 json 格式，使用习惯没有变化。

**Comment by yfdyh000** [comment]
https://github.com/XX-net/XX-Net/pull/3132/files

**Comment by anesliu** [comment]
社长，我也试用了goproxy，发现刚打开的时候效果不错，过一段时间就会出现goodip为0，重启后又好了，请问是什么原因？ip问题吗？但是重启一下回复是什么道理？

**Comment by phuslu** [comment]
@yfdyh000 这个算是修复了一部分吧，貌似还有些问题需要用 gae 代替 direct。

**Comment by phuslu** [comment]
@anesliu 已知问题，优先级最高的一个 bug，正在修复。

**Comment by anesliu** [comment]
@phuslu 感谢解答，感谢一直默默为大家做贡献！！

**Comment by anesliu** [comment]
@yfdyh000 多谢了，我去试试

**Comment by phuslu** [comment]
r459 和 r460 开始尝试修复 “假死” 问题，请帮忙验证。

这个假死问题其实并不是代码上的问题，主要是一些参数调优（使之适应一些不稳定干扰大的 IP)，所以需要大家一起来测试出来。当初 goagent 也是不断调优这些参数才得到一个合理的值。

所以关注这个问题的兄弟，请从 r460 开始验证。

期待大家反馈。

**Comment by phuslu** [comment]
补充一下，目前的参数应该能够较大避免 “假死” 现象了，但是对于那些使用非常稳定的 IP 看 youtube 的场景，有可能性能下降。

期望大家反馈，我尽快让相关参数最优化。

@jasonliul @yeahwu @hcym @jzp820927 @anesliu

**Comment by linhua55** [comment]
@phuslu
有没有可能使这些参数`自适应调节`

**Comment by phuslu** [comment]
@linhua55 有可能的。但是根据我的经验和预估，单靠调整参数就能获得一个不亚于`自适应调节`的效果。

很多些时候`自适应调节`实现的不好反而有害性能。

**Comment by yeahwu** [comment]
刚试了下461版，满屏的黄字，红字，居然没有白字了。能翻，youtube速度有下降，下面是日志
红字部分
```
E0501 23:30:39.957480    9284 handler.go:79] 127.0.0.1:50490 Filter RoundTrip *gae.Filter(&{{[willdd-1251 willddd-1251 willdddd-1251] https appspot.com /_gh/  false false false false [*] map[*.googlegroups.com:google_hk *.googletagmanager.com:google_hk talk.google.com:google_talk talk.l.google.com:google_talk *.ggpht.com:google_hk *.google-analytics.com:google_cn *.google.com:google_hk *.googleapis.com:google_hk talkx.l.google.com:google_talk *.google.com.hk:google_hk dl.google.com:google_cn *.appspot.com:google_hk *.google.cn:google_cn *.googlecode.com:google_hk *.googletagservices.com:google_hk *.googleusercontent.com:google_hk *.gstatic.com:google_hk] map[google_cn:[www.g.cn www.google.cn] google_hk:[58.26.8.88 58.26.8.113 45.121.219.26 45.121.219.16] google_talk:[talk.google.com talk.l.google.com talkx.l.google.com]] [www.google.com books.google.com books.google.com.hk scholar.google.com scholar.google.com.hk translate.google.com translate.google.com.hk] [translate.googleapis.com domains.google.com] map[*.twitter.com:[Access-Control-Allow-Credentials: true Access-Control-Allow-Headers: Authorization, Content-Type, If-Modified-Since, X-Act-As-User-Id, X-B3-Flags, X-Contribute-To-User-Id, X-CSRF-Token, X-Guest-Token, X-TD-Iff-Mtime, X-TD-Mtime-Check, X-Twitter-Auth-Type, X-Twitter-Client, X-Twitter-Client-Version, X-Twitter-Polling, X-Twitter-UTCOffset Access-Control-Allow-Methods: GET, POST, HEAD, PUT, DELETE Access-Control-Allow-Origin: * Access-Control-Max-Age: 1728000 X-Connection-Hash: dfc38d09241e573d311289998bd7e169]] [114.114.114.114 114.114.115.115 168.95.1.1 168.95.192.1 178.79.131.110 199.91.73.222 2001:470:20::2 2001:4860:4860::8844 2001:4860:4860::8888 208.67.220.220 208.67.222.222 209.244.0.3 209.244.0.4 223.5.5.5 223.6.6.6 8.8.4.4 8.8.8.8] [159.106.121.75 203.98.7.65 243.185.187.39 37.61.54.158 59.24.3.173 46.82.174.68 78.16.49.15 8.7.198.45 93.46.8.89 183.207.229.* 183.207.239.*] {{864000 81920 false 180 4 0.05 2 8} false false 180 16 4}} 0xc820012540 0xc8200d20f0 0xc8200d6120 0xc8200d6240 0xc8200d62a0 0xc8200d6300 0xc8200d6360}) error: http2: timeout awaiting response headers
```
黄字部分
```
W0501 23:30:34.829992    9284 gae.go:312] GAE: request "https://0.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=homepage&appver=chat_frontend_20160426.11_p1&VER=8&RID=rpc&SID=4E8927C0EFD0BDDE&CI=1&AID=35&gsessionid=wPMTeg59bKfrYNGrP3jnkR5SCdd81vfA&TYPE=xmlhttp&zx=a5d43q8248qp&t=2" timeout: http2: timeout awaiting response headers, *http.Transport.CloseIdleConnections()
W0501 23:30:35.956652    9284 gae.go:312] GAE: request "https://0.client-channel.google.com/client-channel/gsid" timeout: http2: timeout awaiting response headers, *http.Transport.CloseIdleConnections()
W0501 23:30:36.447888    9284 gae.go:312] GAE: request "https://0.client-channel.google.com/client-channel/channel/cbp?ctype=oz&gsessionid=qf_NwjUqALv4BvKsJvH-xJ5cx7g6GirH&VER=8&MODE=init&zx=pgh0h4yo0ocz&t=1" timeout: http2: timeout awaiting response headers, *http.Transport.CloseIdleConnections()
W0501 23:30:38.830809    9284 gae.go:312] GAE: request "https://0.client-channel.google.com/client-channel/channel/bind?ctype=hangouts&prop=homepage&appver=chat_frontend_20160426.11_p1&VER=8&RID=rpc&SID=4E8927C0EFD0BDDE&CI=1&AID=35&gsessionid=wPMTeg59bKfrYNGrP3jnkR5SCdd81vfA&TYPE=xmlhttp&zx=a5d43q8248qp&t=2" timeout: http2: timeout awaiting response headers, *http.Transport.CloseIdleConnections()
```

**Comment by phuslu** [comment]
@yeahwu 谢谢反馈，看来是 gae.json 的 ResponseHeaderTimeout 的问题，在 r461 改成 16 秒了。

**Comment by cixi666** [comment]
r461,youtube直播卡死的情况好多了。

**Comment by jasonliul** [comment]
@phuslu

Youtube只有1400左右了, 稳定ip, 4天前的.
其他没有变化.

俺没有怎么遇见假死, 不过有时html5的网站, 会有大片红字暂停.
重刷又是正常的.

例如
http://html5speedtest.me/

**Comment by phuslu** [comment]
自测了一下，感觉效果还行，虽然偶尔还有个别页面卡死（一般出现在长时间没有请求的情况, 这个好解，我接下来加个定时器就行了）

总体来说，不会全部”卡死“了，我把 r462 作为正式版发出来看看。

谢谢诸位反馈！

**Comment by phuslu** [comment]
@jasonliul 试下把 gae.json 的 ResponseHeaderTimeout 调大试试，目前是 16 秒。

**Comment by jasonliul** [comment]
E0501 23:50:57.280969    3872 transport.go:60] 127.0.0.1:4091 "G
tml5speedtest.me/blank.dat?1462117850714 HTTP/1.0" (*http.Respon
ted EOF
E0501 23:50:57.282969    3872 transport.go:60] 127.0.0.1:4091 "G
tml5speedtest.me/blank.dat?1462117850714 HTTP/1.0" (*http.Respon
nvalid Read on closed Body

**Comment by phuslu** [comment]
@jasonliul 哦，这个基本就是 ResponseHeaderTimeout 太小导致的。现在我用 r463 版测了一下 html5speedtest, 貌似正常。

**Comment by jasonliul** [comment]
"ResponseHeaderTimeout": 32,
"IdleConnTimeout": 300,

OK了, 看来延时还是缺省大一些好.

**Comment by jasonliul** [comment]
W0502 00:02:47.380585    3940 handler.go:122] IoCopy &http.bodyEOFSignal{body:(*
http.body)(0x13939410), mu:sync.Mutex{state:0, sema:0x0}, closed:false, rerr:err
or(nil), fn:(func(error) error)(0x50ca10), earlyCloseFn:(func() error)(0x50c9b0)
} return 24576 *net.OpError(write tcp 127.0.0.1:8000->127.0.0.1:4621: wsasend: A
n established connection was aborted by the software in your host machine.)

**Comment by phuslu** [comment]
@jasonliul 这类错误请无视，包含了以下字样
```
write tcp 127.0.0.1:8000->127.0.0.1:4621:
```
说明这是一个本地错误，与网络无关，也不会影响使用。

**Comment by yeahwu** [comment]
ResponseHeaderTimeout 调大后，红字出现少了，但是仍然满屏黄字 463版
不影响使用

**Comment by jzp820927** [comment]
既然 P大 都发话了，俺也不能坐以待毙了。

**Comment by jasonliul** [comment]
@phuslu 
收到.
俺其实没有发现新版明显的使用问题.

**Comment by phuslu** [comment]
r465 版设置暂定为 
```
"IdleConnTimeout": 300,
"ResponseHeaderTimeout": 20,
``` 
请关注一下 r465 这个版本的参数是否合适。

**Comment by jasonliul** [comment]
@phuslu 
很好, html5测速正常, 也没有红字了.

有一点很奇怪, gws/gvs混合模式下载速度不够好. GWS+强制http2立刻就能满速. 俺用的CN段是中国谷歌的.

**Comment by phuslu** [comment]
混合模式的确很难兼顾，所以才会提供 ForceHTTP2 来强制用户筛选 IP :laughing:

**Comment by baoziwan** [comment]
刚看youtube时遇到这个错误，Goproxy停止工作，重启才行：
goroutine 1414 [running]:
panic(0x734240, 0xc08200a080)
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/runtime/panic.go:500 +0x19a
net/http.(*persistConn).closeConnIfStillIdle(0xc0845884b0)
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/net/http/transport.go:1240 +0x2c
net/http.(*persistConn).(net/http.closeConnIfStillIdle)-fm()
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/net/http/transport.go:652 +0x27
created by time.goFunc
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/time/sleep.go:129 +0x41

**Comment by phuslu** [comment]
@baoziwan r465 应该修复了。

**Comment by jasonliul** [comment]
@phuslu 

俺其实一直有一个疑问, GoAgent的CN段必须是连号的4个中国谷歌, 不然俺填写10几个, 还说列表太短, 直接跳转HK段.

新版不限制连号或者个数, 其实这个对于下载速度是大大的福音.

**Comment by baoziwan** [comment]
@phuslu 使用的就是r465。

**Comment by phuslu** [comment]
@baoziwan  啊，我再看下。你接下来注意试下新的版本 :)

**Comment by baoziwan** [comment]
R465
同一个youtube视频，又出现错误，停止工作，重启才行：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x50a96c]

goroutine 2632 [running]:
panic(0x734240, 0xc08200a080)
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/runtime/panic.go:500 +0x19a
net/http.(*persistConn).closeConnIfStillIdle(0xc0821642d0)
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/net/http/transport.go:1240 +0x2c
net/http.(*persistConn).(net/http.closeConnIfStillIdle)-fm()
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/net/http/transport.go:652 +0x27
created by time.goFunc
        /home/travis/tmp.20160501162510.8012.goproxy/go/src/time/sleep.go:129 +0x41

**Comment by phuslu** [comment]
@baoziwan 我觉得记得应该修复了，你再下载一次 r465 试下哦，貌似你下到老的了

**Comment by yeahwu** [comment]
循环这种红字，何解？另俺的github是走代理的
```
E0502 00:41:02.481161   10248 transport.go:60] 127.0.0.1:33600 "GAE GET https://live.github.com/_sockets/MTMzMjgzMjg6M2JhYTczYzQ3MmVmNmU4ODY4OGIwNTU1YzdjNzU2OTQ6ZDIxMDBkNDI1NGY3MjRlYTk1ZGY4YWVkMzA5OTc5NjNjZjQ4MWRkYTIxM2Q4M2ExYTExNTMwNjUzOWEwOGY1Ng==--0d7ab4f54ccecd961d08522a2dd2be7d0d660e67 HTTP/1.1" (*http.Response)(nil) http2: timeout awaiting response headers
```
另外还有上上面同样的红字循环出现，不影响使用
goproxy_linux_amd64-r465.tar.xz

**Comment by baoziwan** [comment]
在用r466，视频没问题，但是会出现这样的警告：
E0502 00:53:57.711884   15192 transport.go:60] 127.0.0.1:62523 "GAE GET https://live.github.com/_sockets/MTg0NDUwMjk6YzY5OWM1MmQ3MmU0MjY3Zjk5ZTY1ZmQ2ZTMyNmYzZGE6ZjNiZjU1Y2ViMWRjNjA1OTg2MzNjOTA1MzRlOGI4YTNlYjMyMjQyZGViMGMwYTMyYmU3ZGIwMWExNjdiOGY2ZA==--38028674e784da8a8f40998b5fc6933976fa5042 HTTP/1.1" (*http.Response)(nil) http2: timeout awaiting response headers
W0502 00:53:57.714873   15192 gae.go:312] GAE: request "https://live.github.com/_sockets/MTg0NDUwMjk6YzY5OWM1MmQ3MmU0MjY3Zjk5ZTY1ZmQ2ZTMyNmYzZGE6ZjNiZjU1Y2ViMWRjNjA1OTg2MzNjOTA1MzRlOGI4YTNlYjMyMjQyZGViMGMwYTMyYmU3ZGIwMWExNjdiOGY2ZA==--38028674e784da8a8f40998b5fc6933976fa5042" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()

r466 严重错误，重启才行：
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x50a96c]

goroutine 1196 [running]:
panic(0x734240, 0xc08200a080)
        /home/travis/tmp.20160501163023.10494.goproxy/go/src/runtime/panic.go:500 +0x19a
net/http.(*persistConn).closeConnIfStillIdle(0xc08257c4b0)
        /home/travis/tmp.20160501163023.10494.goproxy/go/src/net/http/transport.go:1240 +0x2c
net/http.(*persistConn).(net/http.closeConnIfStillIdle)-fm()
        /home/travis/tmp.20160501163023.10494.goproxy/go/src/net/http/transport.go:652 +0x27
created by time.goFunc
        /home/travis/tmp.20160501163023.10494.goproxy/go/src/time/sleep.go:129 +0x41

**Comment by phuslu** [comment]
已定位，看起来是 golang 最新版的 bug，先在 goproxy 把 IdleConnTimeout 设为 0 了

请试下 r467

**Comment by baoziwan** [comment]
r467 看起来没问题，会出现以下两个错误，但是不影响使用：
E0502 01:17:33.512677    6456 transport.go:60] 127.0.0.1:64800 "GAE GET https://live.github.com/_sockets/MTg0NDUwMjk6ZjMxMjRhMmUwZDlmM2ZlZDczYTMxM2IwOTM5ZTQ1YWU6YTAxZjhhOTFkNjc2YzU1MTg1M2M4OWQ2OTc5NGQ0MzcyOWRiYjcyMmJmNTRiMWZmYTNkZjYwODMxZmUyNjQzYg==--d7646fe0cdf76ab28624ffd740ccb39ce1839366 HTTP/1.1" (*http.Response)(nil) http2: timeout awaiting response headers
W0502 01:17:33.516129    6456 gae.go:312] GAE: request "https://live.github.com/_sockets/MTg0NDUwMjk6ZjMxMjRhMmUwZDlmM2ZlZDczYTMxM2IwOTM5ZTQ1YWU6YTAxZjhhOTFkNjc2YzU1MTg1M2M4OWQ2OTc5NGQ0MzcyOWRiYjcyMmJmNTRiMWZmYTNkZjYwODMxZmUyNjQzYg==--d7646fe0cdf76ab28624ffd740ccb39ce1839366" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()

天晚了，社长要注意身体，早休息。

**Comment by phuslu** [comment]
@baoziwan 谢谢反馈。

看来 r467 修复了，谢谢。

这两个错误其实正是我想要的，是用来修复“假死”成功以后的提示错误。

晚安诸位，再次感谢。

**Comment by yeahwu** [comment]
俺只想知道，原来白花花的滚屏，现在怎么变成黄色的鸟？
嗯，主要是俺爱美
社长晚安，

**Comment by phuslu** [comment]
@yeahwu 明天再看，晚安 :)

**Comment by jasonliul** [comment]
@phuslu 
社长辛苦, 晚安

**Comment by Lynchie** [comment]
{{864000 81920 false 180 4 0.05 2 8} false false 0 16 20}} 0xc08266e100 0xc0820b81e0 0xc082180060 0xc0821800c0 0xc082180120 0xc082180180 0xc0821801e0}) error: http2: timeout awaiting response headers

**Comment by Lynchie** [comment]
14848 handler.go:122] IoCopy http2.transportResponseBody{cs:(*http2.clientStream)(0xc086056c80)} return 3438 *net.OpError(write tcp 127.0.0.1:8087->127.0.0.1:49872: wsasend: An established connection was aborted by the software in your host machine.)

不影响使用，话说晚上就是好，居然能飙到40000kbps

**Comment by hcym** [comment]
假死没遇过

467版红字很多，速度不错

开多页面非常卡，这情况以前不多

**Comment by jzp820927** [comment]
我觉得如果是不影响使用，不影响性能的红字，黄字报错，干脆就不显示了吧，或者在json 里面增加个日志显示级别，默认是显示正常请求日志，和严重错误日志。

**Comment by phuslu** [comment]
r468 应该好了很多了，可能还有一些，接下来继续看吧。

**Comment by baoziwan** [comment]
@phuslu 使用r471，看Vimeo网站视频的时候，特别是高清模式的时候，容易出现卡住的情况，这时打开其他需要代理的网页就会收到提示“Go Server Fetch Failed: [Over quota: Over quota: ]”，一般过几秒钟就又恢复正常了，goproxy界面显示白字，无错误。不知道是软件还是网站的问题。

**Comment by phuslu** [comment]
@baoziwan 貌似服务端处理“瞬间over quota” 的情况有点问题，我接下来会优化这东东。

你先试下 goagent 的 python 客服务端有没有这个问题。

**Comment by baoziwan** [comment]
@phuslu 想用goagent试试，但是遇到错误ValueError('need more than 2 values to unpack',), retry...，IP是好的，重新上传了一遍appid还是不行。

**Comment by phuslu** [comment]
@baoziwan 那多填几个 appid 到 gae.user.json 呢，5 个左右为佳。

**Comment by baoziwan** [comment]
@phuslu 你是指还是用goproxy，减少appid为5个（我一直是25个）后测试吗？

r471，几乎百分百会遇到“Go Server Fetch Failed: [Over quota: Over quota: ]”。

**Comment by phuslu** [comment]
@baoziwan 谢谢。看来是问题，我接下来关注一下这个问题。

r472 尝试做了初步的修复，有兴趣先试下。

**Comment by baoziwan** [comment]
社长辛苦，r473问题依旧。

**Comment by phuslu** [comment]
@baoziwan 谢谢，我再看看。

**Comment by phuslu** [comment]
@baoziwan r476 对 over quota 频繁出现的问题做了修复，有空请试下。

**Comment by jzp820927** [comment]
这就是效率

**Comment by jasonliul** [comment]
@phuslu 
社长, 检测ip好坏, 之前的绿字很方便.
现在白茫茫一片很难找

**Comment by phuslu** [comment]
@jasonliul r478 改回了 :smiley:

**Comment by baoziwan** [comment]
社长辛苦了。
r476试了一下，还是会出现这样的提示“Go Server Fetch Failed: [Over quota: Over quota: ]”，几秒钟之后就又好了。不过跟之前的版本不一样的是，即便出现提示时，视频也不会停止缓冲。
我想这个我提的这个bug会不会太吹毛求疵了？一般人很少会遇到这样的问题吧？我一般是一边播放1080p的vimeo的页面视频，一边不断重复刷新需要通过代理才能访问的网页，这样才会遇到“Go Server Fetch Failed: [Over quota: Over quota: ]“，一般用户使用的话可能连发现都发现不了。
再次感谢社长。

**Comment by phuslu** [comment]
@baoziwan 嗯， 看来是修复了。报错是避免不了的（毕竟真的超额了）。
但是 r476 版本修复之后，会在后台尝试重试成功。

另外所谓 "吹毛求疵" 言重了，毕竟看视频是 GAE 类代理的一个优势 （谷歌提供免费的午餐，不要钱的流量大家都喜欢哒）

**Comment by baoziwan** [comment]
谢谢社长的辛勤劳动。

**Comment by blob2015** [comment]
辛苦
