### ISSUE TITLE
每次都出现这个问题，求指导，谢谢！

### ISSUE THREAD

**Issue by zou888666** [phuslu/goproxy#661]
先说明，用GOAGENT和XX没有问题，用这个新GO就不知道哪里不对，明明是照着做的啊。
ERROR: logging before flag.Parse: F0503 08:45:15.028769    1328 gae.go:84] storage.ReadJsonConfig("gae.json") failed: invalid character '"' after object key:value pair
goroutine 1 [running, locked to thread]:
github.com/phuslu/glog.stacks(0x954300, 0xc000000000, 0x86, 0xdc)
        /home/travis/tmp.20160502173148.10116.goproxy/gopath/src/github.com/phuslu/glog/glog.go:778 +0xa4
github.com/phuslu/glog.(*loggingT).output(0x937620, 0xc000000003, 0xc082137b00, 0x90e202, 0x6, 0x54, 0x0)
        /home/travis/tmp.20160502173148.10116.goproxy/gopath/src/github.com/phuslu/glog/glog.go:729 +0x2df
github.com/phuslu/glog.(*loggingT).printf(0x937620, 0xc000000003, 0x7a4247, 0x26, 0xc082069ed0, 0x2, 0x2)
        /home/travis/tmp.20160502173148.10116.goproxy/gopath/src/github.com/phuslu/glog/glog.go:655 +0x13f
github.com/phuslu/glog.Fatalf(0x7a4247, 0x26, 0xc082069ed0, 0x2, 0x2)
        /home/travis/tmp.20160502173148.10116.goproxy/gopath/src/github.com/phuslu/glog/glog.go:1157 +0x64
_/home/travis/tmp.20160502173148.10116.goproxy/goproxy/httpproxy/filters/gae.init.1()
        /home/travis/tmp.20160502173148.10116.goproxy/goproxy/httpproxy/filters/gae/gae.go:84 +0x3ea
_/home/travis/tmp.20160502173148.10116.goproxy/goproxy/httpproxy/filters/gae.init()
        /home/travis/tmp.20160502173148.10116.goproxy/goproxy/httpproxy/filters/gae/transport.go:146 +0xa7
_/home/travis/tmp.20160502173148.10116.goproxy/goproxy/httpproxy.init()
        /home/travis/tmp.20160502173148.10116.goproxy/goproxy/httpproxy/httpproxy.go:139 +0x93
main.init()
        /home/travis/tmp.20160502173148.10116.goproxy/goproxy/main.go:62 +0x4e

**Comment by cnshinchan** [comment]
修改json时注意下格式

**Comment by cnrip** [comment]
多了一个双引号
