### ISSUE TITLE
严重错误，通过代理无法登陆网站

### ISSUE THREAD

**Issue by baoziwan** [phuslu/goproxy#675]
@phuslu 
更新goproxy 服务端后，通过任何版本的goproxy都无法登陆某些网站。
比如youtube，vimeo，twitter，github都无法登陆。youtube提示	“登录YouTube时出错。点击此处排查问题。”vemio提示“Unauthorized”，github提示“Your browser did something unexpected. Please contact us if the problem persists.”可以登陆inoreader，但是不显示内容，可以正常登陆gmail。
跟浏览器无关，跟IP无关，跟goproxy版本无关。

**Comment by phuslu** [comment]
看起来的确是服务端的 bug，我重现下。

**Comment by phuslu** [comment]
不好意思，的确是服务端的问题，已修复请更新。

**Comment by baoziwan** [comment]
谢谢社长，已经正常了。

**Comment by sundaqing1969** [comment]
===============================================================
 GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备
。
APPID:sundaqing19852015
12:34 AM Application: sundaqing196919852015
12:34 AM Host: appengine.google.com
12:34 AM Rolling back the update.



出现这个提示，重新部署服务端不成功

**Comment by sundaqing1969** [comment]
原因找到，上传的appid的所在账号必须是谷歌浏览器的你的当前帐号

**Comment by sundaqing1969** [comment]
登录https://appengine.google.com以后，发现木有appid的流量使用情况显示了，代之以使用日志？

**Comment by hcym** [comment]
cd /dev/shm/goproxy-server.gae && python uploader.py 
Traceback (most recent call last):
  File "uploader.py", line 53, in <module>
    println("Loading Google Appengine SDK...")
  File "uploader.py", line 16, in println
    assert type(s) is type(u'')
AssertionError

SDK又升级了？

没法上传

**Comment by sishentibu** [comment]
@sundaqing1969 到这里看https://console.cloud.google.com/appengine/quotadetails

**Comment by sundaqing1969** [comment]
十分感谢 @sishentibu

**Comment by cnshinchan** [comment]
请问 goproxy 服务端代码在那里下的？我还在用 goagent 的呢。

**Comment by cnshinchan** [comment]
找到了  https://github.com/phuslu/goproxy/archive/server.gae.zip

**Comment by hcym** [comment]
@ @phuslu 

用xp才上传成功 

1404的lubuntu死活不行

python uploader.py 
Traceback (most recent call last):
File "uploader.py", line 53, in 
println("Loading Google Appengine SDK...")
File "uploader.py", line 16, in println
assert type(s) is type(u'')
AssertionError


这不应该啊

**Comment by phuslu** [comment]
@hcym 你是不是用 python3 运行的 uploader.py ?

GAE SDK 只能跑在 python 2.7 之下，我刚刚更新了 uploader.py 会检查 python 版本了，如果是 python3 就提示了。

**Comment by hcym** [comment]
没有，我也知道不能用python3

python uploader.py

系统应该默认python 2.7

知道原因就好办了，谢谢老大指点

**Comment by phuslu** [comment]
@hcym 我的错，现在应该修复了。  https://github.com/phuslu/goproxy/commit/8f01cc31c649ef7f8e9e02935d1d0c5670be8ae9

**Comment by hcym** [comment]
ok

差点又要装1604
