### ISSUE TITLE
NewConfig("gae.json") failed: invalid character '"' after array element

### ISSUE THREAD

**Issue by boromeke** [phuslu/goproxy#69]
ERROR: logging before flag.Parse: F0807 11:25:14.735757    1509 gae.go:33] NewConfig("gae.json") failed: invalid character '"' after array element
goroutine 1 [running, locked to thread]:
github.com/golang/glog.stacks(0x80bc00, 0x0, 0x0, 0x0)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x7e6da0, 0x800000003, 0x820972240, 0x7a04df, 0x6, 0x21, 0x0)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:720 +0x2b8
github.com/golang/glog.(*loggingT).printf(0x7e6da0, 0x3, 0x5c18c0, 0x19, 0x8208dbee8, 0x2, 0x2)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0x5c18c0, 0x19, 0x8208dbee8, 0x2, 0x2)
	/home/phuslu/go1.5/gopath/src/github.com/golang/glog/glog.go:1148 +0x5d
github.com/phuslu/goproxy/httpproxy/filters/gae.init.1()
	/home/phuslu/go1.5/gopath/src/github.com/phuslu/goproxy/httpproxy/filters/gae/gae.go:33 +0x223
github.com/phuslu/goproxy/httpproxy/filters/gae.init()
	/home/phuslu/go1.5/gopath/src/github.com/phuslu/goproxy/httpproxy/filters/gae/gae.go:165 +0x153
main.init()
	/home/phuslu/go1.5/gopath/src/github.com/phuslu/goproxy/goproxy/main.go:270 +0xb7

**Comment by Kisesy** [comment]
也许有个标点写错了,你改动了哪里?
如果是appid 应该这样写
	"appids": [
		"xxx","xxx2","xxx3"
记得全部都用半角标点,最后一个appid后面不要加逗号
