### ISSUE TITLE
goproxy服务端上传错误

### ISSUE THREAD

**Issue by erichau** [phuslu/goproxy#702]
已开lesssecureapps，没有用两步认证

APPID:
08:03 PM Application: 
08:03 PM Host: appengine.google.com
08:03 PM Rolling back the update.
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "C:\Users\Eric\Downloads\phuslu-goproxy-e5880c0\phuslu-goproxy-e5880c0\up
loader.py", line 127, in <module>
    main()
  File "C:\Users\Eric\Downloads\phuslu-goproxy-e5880c0\phuslu-goproxy-e5880c0\up
loader.py", line 112, in main
    upload('gae', appid)
  File "C:\Users\Eric\Downloads\phuslu-goproxy-e5880c0\phuslu-goproxy-e5880c0\up
loader.py", line 95, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "google_appengine\google\appengine\tools\appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "google_appengine\google\appengine\tools\appcfg.py", line 2951, in Run
    self.action(self)
  File "google_appengine\google\appengine\tools\appcfg.py", line 5044, in __call
__
    return method()
  File "google_appengine\google\appengine\tools\appcfg.py", line 4397, in Rollba
ck
    self._Rollback()
  File "google_appengine\google\appengine\tools\appcfg.py", line 4442, in _Rollb
ack
    appversion.Rollback(force_rollback)
  File "google_appengine\google\appengine\tools\appcfg.py", line 2362, in Rollba
ck
    force_rollback='1' if force_rollback else '0')
  File "google_appengine\google\appengine\tools\appcfg.py", line 1696, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line
 247, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "google_appengine\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060]
请按任意键继续. . .

**Comment by hcym** [comment]
最近上传是麻烦，对网络要求极高

**Comment by hcym** [comment]
我用goproxy也不行

用hosts和goAgent_ipv6组合拳才成功

**Comment by erichau** [comment]
@hcym 我试了不开代理或者全局ss代理都不行

**Comment by blob2015** [comment]
用vpn吧，一次性搞定。目前依然有不少vpn，因为有一个庞大的群体需要以此来展开工作，他们往往提供试用，也可以在冷清的时候，试一下他们的免费线路
希望那天可以用现存的、可用的GA与GP【可以是已更改端口的，而非必须得默认端口的】来较顺利地实现服务端upload，之前，整整折腾了半天，挨个测试了好些个曾经所谓的软件与办法——比如曾经有帖子说，只要登陆了google的帐号，就可以很快完成，然奇迹没有出现。然后还测试了蓝灯、赛风、cyberghost等等，好久没折腾，活生生折腾了一番

**Comment by hcym** [comment]
主要还是谷歌认证机制

只要能拿到验证码，通过认证

再换代理啊，hosts直传啊，....

慢归慢

总能传完

**Comment by blob2015** [comment]
@hcym 
现在是弹窗，输入一些信息，中间没有其他要求

**Comment by tunnelode** [comment]
这是没有连通的标志。几次都遇到过这种情况，不要灰心快成功了。
下午我用goproxy做代理，上传成功了，这个费劲。推荐用goproxy做翻墙代理。
就是用原来goagent申请的ID，放在gae.json里，然后挑几个比较好的IP，两个就行。在IE里，局域网代理改为127.0.0.1，端口为8087。
如果不行，换另一台PC机或笔记本电脑试试，上传时浏览器开着并已登录appengine.google.com。
反正每次上传APPID部署，都很费劲。

**Comment by jzmswe** [comment]
刚用GP服务端又上传了一次，GP智能几次上传不成功，GP全局一次成功。

**Comment by cai567890** [comment]
我开着SS全局，还是传不上。太高端了

**Comment by hcym** [comment]
可能还是ip质量问题

昨天刚刚用goproxy上传

基本百发百中

**Comment by jzp820927** [comment]
如果 gop 的服务端传不了，可以试试用 xxnet 上传

**Comment by jasonliul** [comment]
现在的上传方式很麻烦

**Comment by jasonliul** [comment]
刚才俺也不成功， 原因很可笑.

关闭你的防火墙， 保存.appcfg_oauth2_tokens下次再用

**Comment by jzp820927** [comment]
我一般重装完系统，第一件事就是关闭防火墙
