### ISSUE TITLE
goproxy配置问题

### ISSUE THREAD

**Issue by silversnow0-0** [phuslu/goproxy#818]
小白一枚。
按照教程配置了一下，然后出现该情况。

ERROR: logging before flag.Parse: F0605 16:10:08.823968    8760 gae.go:92] storage.ReadJsonConfig("gae.json") failed: invalid character '£' after array element
goroutine 1 [running, locked to thread]:
github.com/phuslu/glog.stacks(0x8ef400, 0x0, 0x0, 0x0)
        /home/travis/goproxy.20160604.5449/gopath/src/github.com/phuslu/glog/glog.go:784 +0xac
github.com/phuslu/glog.(*loggingT).output(0x8ddec0, 0x3, 0x10eead20, 0x8bcc84, 0x6, 0x5c, 0x0)
        /home/travis/goproxy.20160604.5449/gopath/src/github.com/phuslu/glog/glog.go:735 +0x26d
github.com/phuslu/glog.(*loggingT).printf(0x8ddec0, 0x3, 0x786b57, 0x26, 0x10e25f68, 0x2, 0x2)
        /home/travis/goproxy.20160604.5449/gopath/src/github.com/phuslu/glog/glog.go:655 +0x14e
github.com/phuslu/glog.Fatalf(0x786b57, 0x26, 0x10e25f68, 0x2, 0x2)
        /home/travis/goproxy.20160604.5449/gopath/src/github.com/phuslu/glog/glog.go:1163 +0x52
_/home/travis/goproxy.20160604.5449/goproxy/httpproxy/filters/gae.init.1()
        /home/travis/goproxy.20160604.5449/goproxy/httpproxy/filters/gae/gae.go:92 +0x182
_/home/travis/goproxy.20160604.5449/goproxy/httpproxy/filters/gae.init()
        /home/travis/goproxy.20160604.5449/goproxy/httpproxy/filters/gae/gaetransport.go:128 +0xbf
_/home/travis/goproxy.20160604.5449/goproxy/httpproxy.init()
        /home/travis/goproxy.20160604.5449/goproxy/httpproxy/httpproxy.go:139 +0xa1
main.init()
        /home/travis/goproxy.20160604.5449/goproxy/main.go:69 +0x57

**Comment by silversnow0-0** [comment]
请告知原因，谢谢。

**Comment by wzdnzd** [comment]
原因说的很明显了啊 storage.ReadJsonConfig("gae.json") failed: invalid character '£' after array element  gae.json文件里出现了'£' 这个不合法的字符，自己检查一下
