### ISSUE TITLE
ERROR: logging before flag.Parse: F0621

### ISSUE THREAD

**Issue by Marcotso** [phuslu/goproxy#896]
OS:windows XP
goproxy R746
按步骤上传服务端后,客户端下载运行,显示如下问题:

ERROR: logging before flag.Parse: F0621 17:40:47.109375    4512 gae.go:96] stora
ge.ReadJsonConfig("gae.json") failed: invalid character '"' after array element
goroutine 1 [running, locked to thread]:
github.com/phuslu/glog.stacks(0xa15d00, 0x0, 0x0, 0x0)
        /home/travis/goproxy.20160620.22437/gopath/src/github.com/phuslu/glog/gl
og.go:784 +0xac
github.com/phuslu/glog.(*loggingT).output(0xa047a0, 0x3, 0x112848c0, 0x9df411, 0
x6, 0x60, 0x0)
        /home/travis/goproxy.20160620.22437/gopath/src/github.com/phuslu/glog/gl
og.go:735 +0x26d
github.com/phuslu/glog.(*loggingT).printf(0xa047a0, 0x3, 0x8590a9, 0x26, 0x11165
f68, 0x2, 0x2)
        /home/travis/goproxy.20160620.22437/gopath/src/github.com/phuslu/glog/gl
og.go:655 +0x14e
github.com/phuslu/glog.Fatalf(0x8590a9, 0x26, 0x11165f68, 0x2, 0x2)
        /home/travis/goproxy.20160620.22437/gopath/src/github.com/phuslu/glog/gl
og.go:1163 +0x52
_/home/travis/goproxy.20160620.22437/goproxy/httpproxy/filters/gae.init.1()
        /home/travis/goproxy.20160620.22437/goproxy/httpproxy/filters/gae/gae.go
:96 +0x182
_/home/travis/goproxy.20160620.22437/goproxy/httpproxy/filters/gae.init()
        /home/travis/goproxy.20160620.22437/goproxy/httpproxy/filters/gae/gaetra
nsport.go:131 +0xc4
_/home/travis/goproxy.20160620.22437/goproxy/httpproxy.init()
        /home/travis/goproxy.20160620.22437/goproxy/httpproxy/httpproxy.go:139 +
0xa1
main.init()
        /home/travis/goproxy.20160620.22437/goproxy/main.go:82 +0x57

**Comment by jzp820927** [comment]
storage.ReadJsonConfig("gae.json") failed: invalid character '"' after array element

已经很明显的提示你了，gae.json 语法错误。

**Comment by Marcotso** [comment]
谢谢,已修改好
