### ISSUE TITLE
checkiptools 如何解决ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by lsnmx** [phuslu/goproxy#908]
谢谢 @xyuanmu 
Traceback (most recent call last):
File "python27.py", line 95, in 
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 1101, in 
main()
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 1084, in main
list_ping(g_googleipfile)
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 989, in list_ping
lastokresult,lasterrorresult = cacheResult.loadLastResult()
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 405, in loadLastResult
errorresult.add(from_string(item))
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 843, in from_string
return reduce(lambda a, b: a << 8 | b, map(int, s.split(".")))
ValueError: invalid literal for int() with base 10: ''

**Comment by blob2015** [comment]
建议：先下载原始版本的试一下，然后如果原始 版本没问题，那么就比较一下。一般，可能会是里面的“编辑”错误，比如ip格式等等

**Comment by jzp820927** [comment]
好像发错地方了的赶脚。

**Comment by lsnmx** [comment]
@jzp820927 没啊，他经常来这

**Comment by jzp820927** [comment]
赶脚应该去他的项目 issues 发更好，说不定解决了，还可以帮更多人。

**Comment by lsnmx** [comment]
@jzp820927 发了，没回应估计 @xyuanmu 泡妞去了

**Comment by jzp820927** [comment]
@xyuanmu 是好像就出现了。X大现在也很少出现了，不知道是不是约好的。

**Comment by yeahwu** [comment]
上次露了一下脸，就再也没看到他了

**Comment by lsnmx** [comment]
@yeahwu 牛人你维护一下，哈哈

**Comment by yeahwu** [comment]
@lsnmx 哎，可惜俺只是个专业打酱油滴！

**Comment by thundery1** [comment]
xxnet那边也好久没见到了呢
